### PR TITLE
Fix AttributeError in Gemma3ForConditionalGeneration and Gemma3ForSequenceClassification when config.return_dict=False

### PR DESCRIPTION
**Pull request by kamalrajkannan78**
# What does this PR do?

- Gemma3ForConditionalGeneration.forward & Gemma3ForSequenceClassification.forward calls self.model() without return_dict=True, so @can_return_tuple silently converts the output to a plain tuple, causing outputs.past_key_values attribute access to crash.

```
venv/lib/python3.12/site-packages/transformers/utils/generic.py:841: in wrapper
    output = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
venv/lib/python3.12/site-packages/transformers/models/gemma3/modeling_gemma3.py:1127: in forward
    past_key_values=outputs.past_key_values,
                    ^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: 'tuple' object has no attribute 'past_key_values'
```

- **Fix:** pass return_dict=True explicitly to self.model(...) in both classes, consistent with how Gemma3Model.forward already does for its inner self.language_model(...) call. The caller's return_dict=False preference is still honored by           @can_return_tuple on the outer forward at the boundary.               

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@zucchini-nlp this is related to the `Gemma3Model` wrapper introduced in #37033, would appreciate your review!

### CODE REVIEW

**Review by zucchini-nlp — COMMENTED** [review]
Interesting, `can_return_tuple` already would force-set `return_dict=True` before calling the forward. Could you provide a reproducer?

**Comment by kamalrajkannan78** [comment]
> Interesting, `can_return_tuple` already would force-set `return_dict=True` before calling the forward. Could you provide a reproducer?

pip install transformers==5.5.0

```
import torch
from transformers import AutoModelForImageTextToText, AutoProcessor
from loguru import logger

def test_gemma3():
    
    model_id = "google/translategemma-4b-it"
    processor = AutoProcessor.from_pretrained(model_id)
    model = AutoModelForImageTextToText.from_pretrained(model_id,dtype=torch.bfloat16,return_dict=False)
    logger.info("model={}",model)
    
    # ---- Text Extraction and Translation ----
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "source_lang_code": "cs",
                    "target_lang_code": "de-DE",
                    "url": "https://c7.alamy.com/comp/2YAX36N/traffic-signs-in-czech-republic-pedestrian-zone-2YAX36N.jpg",
                },
            ],
        }
    ]

    inputs = processor.apply_chat_template(
        messages, tokenize=True, add_generation_prompt=True, return_dict=True, return_tensors="pt"
    )
    
    for key, value in inputs.items():
        if isinstance(value, torch.Tensor) and value.dtype == torch.float32:
            inputs[key] = value.to(torch.bfloat16)
    
    
    with torch.no_grad():
        outputs = model(**inputs)
        
    logger.info("outputs={}",outputs)

```

Error log - [apr7_gemma3_v5_5_0.log](https://github.com/user-attachments/files/26540633/apr7_gemma3_v5_5_0_bf.log)

**Review by zucchini-nlp — APPROVED** [review]
Huh indeed, i guess I am confusing it with another helper. Could you mark PR as ready for review?

I think there might be more models so if you have bandwidth, would be great to fix all at once. Dont worry if not :)

**Review by zucchini-nlp — APPROVED** [review]
Huh indeed, i guess I am confusing it with another helper. Could you mark PR as ready for review?

I think there might be more models so if you have bandwidth, would be great to fix all at once. Dont worry if not :)

**Comment by zucchini-nlp** [comment]
and run `make fix-repo` pls to make CI ✅

**Comment by kamalrajkannan78** [comment]
> Huh indeed, i guess I am confusing it with another helper. Could you mark PR as ready for review?
> 
> I think there might be more models so if you have bandwidth, would be great to fix all at once. Dont worry if not :)

Sorry, I don’t have the bandwidth to look into other models at the moment. However, if I come across similar issues in other models in the future, I’ll make sure to raise a PR to fix them as well.

Thanks for the review!

**Comment by zucchini-nlp** [comment]
To fix CI with `make fix-repo`, you'd need to apply the changes in modular and if needed, in Paligemma files. Then I'll merge

**Comment by kamalrajkannan78** [comment]
> To fix CI with `make fix-repo`, you'd need to apply the changes in modular and if needed, in Paligemma files. Then I'll merge

- I've applied the fix in modular_gemma3.py and ran make fix-repo — all 14 checks pass locally. I also checked Paligemma but it doesn't have the same pattern (no missing return_dict in internal model calls).
- The tests_hub / run_tests failure is due to a HuggingFace Hub 401 authentication error when downloading test fixtures (cow_beach_1.png from hf-internal-testing/fixtures-captioning), not related to my code  change. Could you please re-trigger the CI?   

Screenshot 2026-04-08 at 10 36 26 PM
