### ISSUE TITLE
Unable to follow Object Detection Task Example due to ImageProcessor error

### ISSUE THREAD

**Issue by govindrai** [huggingface/transformers#25666]
### System Info

transformers 4.3.2
python 3.10
using google colab

### Who can help?

@amyeroberts, @sgugger, @stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
Follow [official tutorial](https://huggingface.co/docs/transformers/v4.32.0/en/tasks/object_detection) instructions:
After applying a transform function to the CPPE5 dataset and trying to load a single element fails with the following error:

```
TypeError                                 Traceback (most recent call last)
[<ipython-input-75-e2a7222a96ab>](https://localhost:8080/#) in <cell line: 22>()
     20 
     21 cppe5["train"] = cppe5["train"].with_transform(transform_aug_ann)
---> 22 cppe5["train"][15]

9 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/detr/image_processing_detr.py](https://localhost:8080/#) in <listcomp>(.0)
   1285             if annotations is not None:
   1286                 annotations = [
-> 1287                     self.normalize_annotation(
   1288                         annotation, get_image_size(image, input_data_format), input_data_format=input_data_format
   1289                     )

TypeError: DetrImageProcessor.normalize_annotation() got an unexpected keyword argument 'input_data_format'
```

Here's a colab notebook so you test/run it easily. Go to the last step to view the error:
https://colab.research.google.com/drive/1WtwFcW7_N5N7VLsoswx2U4O8CBkCRNc4?usp=sharing

### Expected behavior

I expect to not encounter a failure and continue the tutorial.

**Comment by ArthurZucker** [comment]
cc @amyeroberts seems to come from #25464

**Comment by amyeroberts** [comment]
Hi @govindrai, thanks for raising this issue! 

Yes, this was a bug introduced in #25464. A fix was merged in yesterday in #25643 on main. Installing from source should resolve the issue.

**Comment by amyeroberts** [comment]
@govindrai The fix has now been included as part of a [patch release](https://github.com/huggingface/transformers/releases/tag/v4.32.1) and can be directly installed from pypi with `pip install transformers`
