### PR TITLE
Paligemma: fix generation with Gemma2

### LINKED ISSUE #36029: PaliGemma2 doesn't work with transformers v4.48.2
### System Info

- `transformers` version: 4.48.2
- Platform: Linux-6.12.8-200.fc41.x86_64-x86_64-with-glibc2.40
- Python version: 3.13.1
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.5.2
- Accelerate version: 1.3.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0a0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no
- Using GPU in script?: yes
- GPU type: AMD Radeon RX 7600 XT

### Who can help?

_No response_

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Run [example script in PaliGemma2 model card](https://huggingface.co/google/paligemma2-3b-pt-224#use-in-transformers) with transfomers v4.48.2
2. It failed with `TypeError: PaliGemmaForConditionalGeneration.forward() got an unexpected keyword argument 'last_cache_position'. (snipped)`

If I try the same thing with transformers v4.48.1 it works.

### Expected behavior

It should be successful.

---

This PR https://github.com/huggingface/transformers/pull/35681 which is released as v4.48.2, introduced `last_cache_position` kwarg to Gemma2 model.

As a side effect of this, the same  `last_cache_position` kwarg may be passed to PaliGemma2.
But PaliGemma2 doesn't know `last_cache_position` kwarg, and [the example script in model card of PaliGemma2](https://huggingface.co/google/paligemma2-3b-pt-224#use-in-transformers) fails to run with the following error:

```
TypeError: PaliGemmaForConditionalGeneration.forward() got an unexpected keyword argument 'last_cache_position'. Did you mean 'cache_position'?
```

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/36029 and adds tests for the model, imo we need tests with different LM backbone because Gemma-2 is special

This is a quick fix but I think we should make this kind of fix on LM work out-of-the-box, by adding it as `kwargs` for example. Most LMs accept `loss_kwargs` thus we can make all multimodal models also accept kwargs that are simply passed further to the LM. WDYT?

### CODE REVIEW

File: src/transformers/models/paligemma/modeling_paligemma.py [hunk 1]
```diff
@@ -537,6 +536,7 @@ def forward(
             return_dict=return_dict,
             cache_position=cache_position,
             logits_to_keep=logits_to_keep,
+            last_cache_position=last_cache_position,
```
Comment (molbap) [inline src/transformers/models/paligemma/modeling_paligemma.py:539]: Agreed that passing kwargs here should work ootb, maybe with a typed `LanguageModelKwars` or something similar?

Comment (zucchini-nlp) [reply src/transformers/models/paligemma/modeling_paligemma.py:539]: yeah, maybe we cannot use Unpack since we don't know which kwargs an LM has or which LM is used. But just making `kwargs` an addition for all multimodal models will help us to prevent these bugs in the future

I think for that we'd need to update all VLMs, so if Arthur is oke I can add `kwargs` within this PR also

Comment (ArthurZucker) [reply src/transformers/models/paligemma/modeling_paligemma.py:539]: Kwargs are fine for me

**Review by ArthurZucker — COMMENTED** [review]
we can just use kwargs no?

**Comment by zucchini-nlp** [comment]
I think making it explicit that kwargs will be used by an only an LM was better

**Review by Cyrilvallez — APPROVED** [review]
Fine with me! Thanks a lot!

File: tests/models/paligemma2/test_modeling_paligemma2.py
Comment (ArthurZucker) [inline tests/models/paligemma2/test_modeling_paligemma2.py:1]: let's say that an integration test is most welcome as well!

**Review by ArthurZucker — APPROVED** [review]

**Comment by ArthurZucker** [comment]
For transparency, this commit needs to be modified for the patch, only applying changes for PaliGemnma2

File: tests/models/paligemma2/test_modeling_paligemma2.py
Comment (zucchini-nlp) [reply tests/models/paligemma2/test_modeling_paligemma2.py:1]: yeah, was quite low in priority for the patch so I decided to skip it for now :)

**Comment by hiyouga** [comment]
Hi @zucchini-nlp @ArthurZucker , I find this PR can lead to an abnormal loss value if gradient accumulation is enabled. Initially reported in https://github.com/hiyouga/LLaMA-Factory/issues/7443 , the trainer assumes these model accept loss kwargs because of the existence of `lm_kwargs` (1), but actually they do not (2), resulting in an unexpected loss value. This is also related to the gradient accumulation fix PR #34511 , cc @muellerzr 

1. https://github.com/huggingface/transformers/blob/v4.50.0/src/transformers/trainer.py#L633-L640
2. https://github.com/huggingface/transformers/blob/v4.50.0/src/transformers/models/llava/modeling_llava.py#L460-L464

**Comment by hiyouga** [comment]
> This is a quick fix but I think we should make this kind of fix on LM work out-of-the-box, by adding it as kwargs for example. Most LMs accept loss_kwargs thus we can make all multimodal models also accept kwargs that are simply passed further to the LM. WDYT?

Yeah, it is true that most LMs accept such kwargs, but multimodal models compute the loss themselves, unless we reuse the loss computed by the language model part.

**Comment by hiyouga** [comment]
A similar bug report regarding the gemma3 model: https://github.com/hiyouga/LLaMA-Factory/issues/7416

**Comment by zucchini-nlp** [comment]
> Yeah, it is true that most LMs accept such kwargs, but multimodal models compute the loss themselves, unless we reuse the loss computed by the language model part.

Yep, I will look into that and find a better solution

**Comment by hiyouga** [comment]
@zucchini-nlp Hi, I'm currently deeply occupied with writing my thesis and really don't have much spare time at the moment. Unfortunately, I won't be able to submit the PR. Thanks for understanding!

**Comment by zucchini-nlp** [comment]
@hiyouga yeah, no problem :)
