### PR TITLE
[safetensors] don't use in `torch<1.10`

### PR DESCRIPTION
**Pull request by stas00**
`safetensors` only seems to work with pt>=1.10. This PR fixes this breakage:

```
python -c 'import sys; from transformers import AutoModel; AutoModel.from_pretrained(sys.argv[1])'  "bigscience/bigscience-small-testing"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/modeling_utils.py", line 2424, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/safetensors/torch.py", line 101, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'frombuffer'
```

### CODE REVIEW

File: src/transformers/utils/import_utils.py [hunk 1]
```diff
@@ -577,7 +577,10 @@ def is_optimum_available():
 
 
 def is_safetensors_available():
-    return importlib.util.find_spec("safetensors") is not None
+    if version.parse(_torch_version) >= version.parse("1.10"):
```
Comment (ydshieh) [inline src/transformers/utils/import_utils.py:580]: should we check if torch is available before doing `version.parse(_torch_version)`. Otherwise, I am not sure what will happen (for `version.parse`) with `_torch_version = "N/A"`.

Comment (stas00) [reply src/transformers/utils/import_utils.py:580]: ah, the usual gotcha for me! yes! thank you, @ydshieh

Comment (ydshieh) [reply src/transformers/utils/import_utils.py:580]: cc @Narsil 🙏

Comment (stas00) [reply src/transformers/utils/import_utils.py:580]: which one?

A. 
```
def is_safetensors_available():
    if is_torch_available():
        if version.parse(_torch_version) >= version.parse("1.10"):
            return importlib.util.find_spec("safetensors") is not None
        else:
            return False
    else:
        return importlib.util.find_spec("safetensors") is not None
```

B. 
```
def is_safetensors_available():
    if is_torch_available() and version.parse(_torch_version) >= version.parse("1.10"):
        return importlib.util.find_spec("safetensors") is not None
    else:
        return False
```

Comment (ydshieh) [reply src/transformers/utils/import_utils.py:580]: But personally, I think a (ugly) hack is: if 

torch is not available ==> return importlib.util.find_spec("safetensors") is not None
torch is avaialalbe + version.parse(_torch_version) >= version.parse("1.10") ==> same

otherwise:

return False

Comment (stas00) [reply src/transformers/utils/import_utils.py]: so A. this is what I have just pushed. please check if it works for you.

**Review by sgugger — APPROVED** [review]
Thanks for the quick fix!

File: src/transformers/utils/import_utils.py (hunk 1 above)
Comment (ydshieh) [reply src/transformers/utils/import_utils.py]: works for me, and since Sylvain approved, you can go ahead once CI is green.

(I personally don't know if `safetensors` is relevant to `tensorflow` - I heard about it once, but it might be relevant just in future)

Comment (sgugger) [reply src/transformers/utils/import_utils.py]: It is relevant to TensorFlow as well as PyTorch. safetensors weights are fraework-agnostic.

**Comment by sgugger** [comment]
I need a PR merged to test my fix for the torch and tf run which is broken on main (but the fix itself does not trigger any tests). This one seems a good candidate so merging now and will keep an eye on the test :-)

**Comment by thomasw21** [comment]
Shouldn't those be fixed in safetensors instead? ie here https://github.com/huggingface/safetensors/blob/5c1d366813e46c6f9f2c71aa8b89e0c916a92b2f/bindings/python/setup.py#L23 ?

**Comment by Narsil** [comment]
Also, I left torch version out on purpose at the time, as I wasn't sure about the support policy and wether or not supporting older version was worth the effort (since they require a lot more handling from safetensors itself).
