### ISSUE TITLE
Make all Transformer models compatible with model parallelism

### ISSUE THREAD

**Issue by sgugger** [huggingface/transformers#22561]
Accelerate makes it easy to load a model on multiple GPUs with `device_map="auto"`. This in turn allows users to train model with naive model parallelism if they have several GPUs.

A problem that happens in Transformers, with model with heads (so not XxxModel but for instance XxxModelForSequenceClassification) is that the labels end up on a different device than the logits and there is a device mistmatch error.

Thankfully, there is an easy fix for that! #22535 shows how to fix this for T5 by just moving the labels to the same device as the logits they are compared to. This is a noop when the devices are the same, and fixes the issue if devices are different.

We would like help from the community to extend this to all models that support model parallelism, which are:
- [x] BART
- [x] BigBirdPegasus
- [x] BLIP2
- [x] BLOOM
- [x] BridgeTower
- [x] CamemBERT
- [ ] CLIP
- [ ] CLIPSeg
- [ ] CodeGen
- [x] Data2Vec Text
- [x] Deit
- [x] ESM
- [x] GPT-2
- [x] GPT-Neo
- [x] GPT-NeoX
- [x] GPT-NeoX Japanese
- [ ] GPT-J
- [x] GPT-San
- [ ] JukeBox
- [ ] Lilt
- [x] LLaMA (`LlamaForSequenceClassification` only)
- [x] Longformer
- [x] LongT5
- [ ] Luke
- [ ] M2M100
- [x] mBART
- [x] mT5
- [ ] NLLB
- [ ] OPT
- [ ] Owl-ViT
- [ ] Pix2Struct
- [x] PLBART
- [x] RoBERTa
- [x] RoBERTa PreLayerNorm
- [ ] SwitchTransformer
- [x] T5
- [ ] Vilt
- [x] ViT
- [x] ViT-Hybrid
- [ ] Whisper
- [x] XLM-RoBERTa

If you would like to grab one of those models and apply the same fix as #22535 to all the model with heads, please leave a comment here!

**Comment by muaid-mughrabi** [comment]
I think I can help with this Issue :)

**Comment by innat** [comment]
Thanks @sgugger for creating this issue, just-in-time. I've tried to run transformer models in parallel; for some model i.e. `facebook/opt-1.3b`, it works with some tricks but for some model i.e.. gpt-j-6b, I've faced following issue 

```
AttributeError: 'GPTJModel' object has no attribute 'first_device'
```

Full logs

> ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 20
     12 trainer = Trainer(
     13     model=model,
     14     args=training_args,
     15     data_collator=data_collator,
     16     train_dataset=train_dataset,
     17 )
     19 model.config.use_cache = False 
---> 20 trainer.train()
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/transformers/trainer.py:1639, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1634     self.model_wrapped = self.model
   1636 inner_training_loop = find_executable_batch_size(
   1637     self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size
   1638 )
-> 1639 return inner_training_loop(
   1640     args=args,
   1641     resume_from_checkpoint=resume_from_checkpoint,
   1642     trial=trial,
   1643     ignore_keys_for_eval=ignore_keys_for_eval,
   1644 )
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/transformers/trainer.py:1906, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1904         tr_loss_step = self.training_step(model, inputs)
   1905 else:
-> 1906     tr_loss_step = self.training_step(model, inputs)
   1908 if (
   1909     args.logging_nan_inf_filter
   1910     and not is_torch_tpu_available()
   1911     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   1912 ):
   1913     # if loss is nan or inf simply add the average of previous logged losses
   1914     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/transformers/trainer.py:2652, in Trainer.training_step(self, model, inputs)
   2649     return loss_mb.reduce_mean().detach().to(self.args.device)
   2651 with self.compute_loss_context_manager():
-> 2652     loss = self.compute_loss(model, inputs)
   2654 if self.args.n_gpu > 1:
   2655     loss = loss.mean()  # mean() to average on multi-gpu parallel training
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/transformers/trainer.py:2684, in Trainer.compute_loss(self, model, inputs, return_outputs)
   2682 else:
   2683     labels = None
-> 2684 outputs = model(**inputs)
   2685 # Save past state if it exists
   2686 # TODO: this needs to be fixed and made cleaner later.
   2687 if self.args.past_index >= 0:
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/accelerate/hooks.py:165, in add_hook_to_module.<locals>.new_forward(*args, **kwargs)
    163         output = old_forward(*args, **kwargs)
    164 else:
--> 165     output = old_forward(*args, **kwargs)
    166 return module._hf_hook.post_forward(module, output)
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py:869, in GPTJForCausalLM.forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
    867 # Set device for model parallelism
    868 if self.model_parallel:
--> 869     torch.cuda.set_device(self.transformer.first_device)
    870     hidden_states = hidden_states.to(self.lm_head.weight.device)
    872 # make sure sampling in fp16 works correctly and
    873 # compute loss in fp32 to match with mesh-tf version
    874 # https://github.com/EleutherAI/gpt-neo/blob/89ce74164da2fb16179106f54e2269b5da8db333/models/gpt2/gpt2.py#L179
File /opt/conda/envs/gpt_neox/lib/python3.9/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'GPTJModel' object has no attribute 'first_device'

---

cc. @younesbelkada

**Comment by younesbelkada** [comment]
hi @innat 
I believe you are using the trainer, and setting `setattr(model, 'is_model_parallel', True)`. If that's the case you don't need to set that anymore, and use the `main` branch of `transformers` ( https://github.com/huggingface/transformers/pull/22532 )instead

**Comment by innat** [comment]
@sgugger 
Sorry for the unwanted noise, it's removed. I will create new one with code. Thanks.

**Comment by iamarunbrahma** [comment]
I would like to work on this issue :)

**Comment by kaustubh-s1** [comment]
Hi, I can take this up 🙌🏻

**Comment by zsc** [comment]
Indeed, this fix is required for BLOOM. https://github.com/huggingface/transformers/compare/main...zsc:transformers:main

**Comment by TerryCM** [comment]
Just to make sure  does LlamaForCausalLM supports this feature already?(https://github.com/huggingface/transformers/issues/22546 ) it seems that, still there are some errors when using `device_map="auto"`

**Comment by mollerup23** [comment]
Hi, I'd like to pick up the GPT-2 model!

**Comment by xssChauhan** [comment]
Hi! I am taking this up for `LlamaForSequenceClassification`.

**Comment by kooshi** [comment]
> Just to make sure does `LlamaForCausalLM` supports this feature already?(#22546 ) it seems that, still there are some errors when using `device_map="auto"` for this task.

It does (#22329).  I have started seeing similar errors to #22546, but only after updating my drivers from 525 to 530, similar to https://github.com/huggingface/transformers/issues/22546#issuecomment-1498348442

**Comment by innat** [comment]
@younesbelkada @sgugger 
Does this fix (moving label/logit to same device) supposed to work (model parallelism) for all models (listed above)? Or, a crucial step toward it? Also, this design fix is only for pytorch model and not for jax or tf?

**Comment by younesbelkada** [comment]
I think it is supposed to work for all models listed above, as long as you are loading your model with `device_map=xxx`. And yes this should be for Pytorch only, though I am not really aware of how model parallelism work on TF & Jax

**Comment by innat** [comment]
> I think it is supposed to work for all models listed above, as long as you are loading your model with device_map=xxx

I tried with such fix here https://github.com/huggingface/transformers/pull/22591#issuecomment-1498013324 but sadly it didn't work out. Any catch?

**Comment by innat** [comment]
@sgugger 
As the goal of this ticket is to enable model parallelism with easy fix, have the merged PR(s) checked on multi-gpu? I couldn't find any test script here https://github.com/huggingface/transformers/pull/22663/ regarding that .

**Comment by shahad-mahmud** [comment]
I would love to work with BridgeTower

**Comment by trantuantdt** [comment]
Hi. I would like to try with "Whisper"

**Comment by mayankagarwals** [comment]
Taking this up for the remaining GPT models

**Comment by jprivera44** [comment]
Hello, I just completed the GPT-J code, where should I write the documentation? Just filling in the PR now.

**Comment by jprivera44** [comment]
> Hello, I just completed the GPT-J code. Just filling in the PR now. FYI @mayankagarwals if you're still looking into GPT-J.

**Comment by oscar-garzon** [comment]
Hello! I'd like to work in Whisper model

**Comment by abhigyan631** [comment]
Hi, is there any model on which I can work, please? Thanks.

**Comment by Tanmaypatil123** [comment]
Is there any remaining model on which I can work ?  Thanks .

**Comment by JuheonChu** [comment]
@sgugger Hello, can I work on the JukeBox?

**Comment by Batese2001** [comment]
@sgugger I would love to work on CodeGen if it is unclaimed

**Comment by katiele47** [comment]
Hi @sgugger I can work on `Luke` if it has not been taken

**Comment by VomV** [comment]
@sgugger I would like to work on SwitchTransformer, if not taken.

**Comment by sushmanthreddy** [comment]
@sgugger I think all transformers are covered, I have checked for others also...for example, switch transformers have parallelism implemented already. i think we can close this issue

**Comment by sgugger** [comment]
Indeed, all models have been covered. Thanks a lot everyone!
