### PR TITLE
Add video text to text docs

### PR DESCRIPTION
**Pull request by merveenoyan**
Adding video-text-to-text task guide

@zucchini-nlp @NielsRogge @amyeroberts @stevhliu

### CODE REVIEW

**Comment by merveenoyan** [comment]
There seems to be an issue with Llava, in the latest stable some image tokens are cropped, i.e. when I pass 12 downsampled frames and 12 <image> tokens it tells me to add 13 image tokens instead. It's fixed in main, but now I get `
TypeError: LlavaForConditionalGeneration.forward() got an unexpected keyword argument 'num_logits_to_keep'` from `result = self._sample(input_ids, logits_processor=prepared_logits_processor)`.

**Comment by zucchini-nlp** [comment]
Caused by https://github.com/huggingface/transformers/pull/31292, will work on it

File: docs/source/en/tasks/video_text_to_text.md [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+⚠️ Note that this file is in Markdown but contain specific syntax for our doc-builder (similar to MDX) that may not be
+rendered properly in your Markdown viewer.
+
+-->
+
+# Video-text-to-text
+
+[[open-in-colab]]
+
+Video-text-to-text models, also known as video language models or vision language models with video input, are language models that take an video input. These models can tackle various tasks, from visual question answering to video captioning.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:21]:
```suggestion
Video-text-to-text models, also known as video language models or vision language models with video input, are language models that take a video input. These models can tackle various tasks, from visual question answering to video captioning. 
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+
+-->
+
+# Video-text-to-text
+
+[[open-in-colab]]
+
+Video-text-to-text models, also known as video language models or vision language models with video input, are language models that take an video input. These models can tackle various tasks, from visual question answering to video captioning. 
+
+These models are almost the same as [image-text-to-text](../image_text_to_text.md) models by means of architecture. They have some adjustments and additions to their architecture to accept video data, which is essentially image frames with temporal dependencies. Some `image-text-to-text` models take in multiple images, but this condition alone is inadequate for the model to accept videos. Moreover, `video-text-to-text` models are often trained with all vision modalities, each row might have videos, multiple videos, images and multiple images. Some of these models can also take interleaved input, i.e. one can refer to a specific video inside text through inputting video token in text like "What is happening in this video? `<video>`".
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:23]:
```suggestion
These models have nearly the same architecture as [image-text-to-text](../image_text_to_text.md) models except for some changes to accept video data, which are essentially image frames with temporal dependencies. Some image-text-to-text models take in multiple images, but this alone is inadequate for a model to accept videos. Moreover, video-text-to-text models are often trained with all vision modalities. Each row might have videos, multiple videos, images and multiple images. Some of these models can also take interleaved inputs. For example, you can refer to a specific video inside a string of text by adding a video token in text like "What is happening in this video? `<video>`". 
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+
+In this guide, we provide a brief overview of video LMs and show how to use them with Transformers for inference.
+
+To begin with, there are multiple types of video LMs:
+- base models used for fine-tuning
+- chat fine-tuned models for conversation
+- instruction fine-tuned models
+
+This guide focuses on inference with an instruction-tuned model, [llava-hf/llava-interleave-qwen-7b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-7b-hf) which can take in interleaved data. Alternatively you can try [llava-interleave-qwen-0.5b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-0.5b-hf)] if your hardware doesn't allow running a 7B model.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:32]:
```suggestion
This guide focuses on inference with an instruction-tuned model, [llava-hf/llava-interleave-qwen-7b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-7b-hf) which can take in interleaved data. Alternatively, you can try [llava-interleave-qwen-0.5b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-0.5b-hf)] if your hardware doesn't allow running a 7B model.
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 4]
```diff
@@ -0,0 +1,146 @@
...
+import torch
+model_id = "llava-hf/llava-interleave-qwen-0.5b-hf"
+
+processor = LlavaProcessor.from_pretrained(model_id)
+
+model = LlavaForConditionalGeneration.from_pretrained(model_id, torch_dtype=torch.float16)
+model.to("cuda")
+```
+
+Some models directly consume `<video>` token, and some take in `<image>` tokens inserted as many as the number of sampled frames. This model handles videos in latter fashion. We will write a simple utility to handle image tokens and another to get a video from a url and sample frames from it.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:53]:
```suggestion
Some models directly consume the `<video>` token, and others accept `<image>` tokens equal to the number of sampled frames. This model handles videos in the latter fashion. We will write a simple utility to handle image tokens, and another utility to get a video from a url and sample frames from it. 
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 5]
```diff
@@ -0,0 +1,146 @@
...
+  <div class="video-container">
+    <video width="400" controls>
+      <source src="https://huggingface.co/spaces/merve/llava-interleave/resolve/main/cats_2.mp4" type="video/mp4">
+    </video>
+  </div>
+</div>
+
+Now we can preprocess the inputs.
+
+This model has a prompt template that looks like following. First we'll put all sampled frames into one list. Since we have eight frames in each video, we will insert 12 `<image>` tokens to our prompt. Note that we are adding `assistant` at the end to trigger model to give answers. We can then preprocess.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:123]:
```suggestion
This model has a prompt template that looks like following. First, we'll put all the sampled frames into one list. Since we have eight frames in each video, we will insert 12 `<image>` tokens to our prompt. Add `assistant` at the end of the prompt to trigger the model to give answers. Then we can preprocess.
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+
+```python
+user_prompt = "Are these two cats in these two videos doing the same thing?"
+toks = "<image>" * 12
+prompt = "<|im_start|>user"+ toks + f"\n{user_prompt}<|im_end|><|im_start|>assistant"
+inputs = processor(prompt, images=videos).to(model.device, model.dtype)
+```
+
+
+We can now infer. The model will output the question we've input and the answer, so we will take the text that is after our prompt and the "assistant" part.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:133]:
```suggestion
Use [`~GenerationMixin.generate`] for inference. The model outputs the question in our input and answer, so only take the text after the prompt and `assistant` part. 
```

File: docs/source/en/tasks/video_text_to_text.md [hunk 7]
```diff
@@ -0,0 +1,146 @@
...
+print(processor.decode(output[0][2:], skip_special_tokens=True)[len(user_prompt)+10:])
+
+# The first cat is shown in a relaxed state, with its eyes closed and a content expression, while the second cat is shown in a more active state, with its mouth open wide, possibly in a yawn or a vocalization.
+
+
+```
+
+And voila! 
+
+The chat templates and token streaming for `video-text-to-text` models work in similar fashion as [image-text-to-text](../image_text_to_text.md) models, so if you would like to learn more, please visit the task guide for it.
```
Comment (stevhliu) [inline docs/source/en/tasks/video_text_to_text.md:146]:
```suggestion
To learn more about chat templates and token streaming for video-text-to-text models, refer to the [image-text-to-text](../image_text_to_text) task guide because these models work similarly.
```

**Review by stevhliu — APPROVED** [review]
Very nice, thanks for adding! 🔥 

Remember to add the doc to the `toctree`!

**Review by amyeroberts — COMMENTED** [review]
LGTM - thanks for adding! ❤️

**Review by amyeroberts — APPROVED** [review]

**Review by zucchini-nlp — COMMENTED** [review]
Yay, thanks for adding this! Looks good but I wan thinking of adding an inference with pure VideoLLMs, WDYT?

File: docs/source/en/tasks/video_text_to_text.md [hunk 8]
```diff
@@ -0,0 +1,145 @@
...
+  <div class="video-container">
+    <video width="400" controls>
+      <source src="https://huggingface.co/spaces/merve/llava-interleave/resolve/main/cats_2.mp4" type="video/mp4">
+    </video>
+  </div>
+</div>
+
+Now we can preprocess the inputs.
+
+This model has a prompt template that looks like following. First we'll put all sampled frames into one list. Since we have eight frames in each video, we will insert 12 `<image>` tokens to our prompt. Note that we are adding `assistant` at the end to trigger model to give answers. We can then preprocess.
```
[the remark this answers is not in the document]
Comment (merveenoyan) [reply docs/source/en/tasks/video_text_to_text.md]: sorry I changed later to 7B model so should've modified this

File: docs/source/en/tasks/video_text_to_text.md [hunk 9]
```diff
@@ -0,0 +1,145 @@
...
+
+In this guide, we provide a brief overview of video LMs and show how to use them with Transformers for inference.
+
+To begin with, there are multiple types of video LMs:
+- base models used for fine-tuning
+- chat fine-tuned models for conversation
+- instruction fine-tuned models
+
+This guide focuses on inference with an instruction-tuned model, [llava-hf/llava-interleave-qwen-7b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-7b-hf) which can take in interleaved data. Alternatively, you can try [llava-interleave-qwen-0.5b-hf](https://huggingface.co/llava-hf/llava-interleave-qwen-0.5b-hf) if your hardware doesn't allow running a 7B model.
```
[the remark this answers is not in the document]
Comment (merveenoyan) [reply docs/source/en/tasks/video_text_to_text.md:32]: I thought most models are coming out as interleaved so actually using an interleaved example is good since they're harder to get started with. I can add simple VideoLLM example separately with chat templates though

[the remark this answers is not in the document]
Comment (zucchini-nlp) [reply docs/source/en/tasks/video_text_to_text.md:32]: Yes, they are mostly interleaved. The difference with llava-interleave is that we didn't add a new model for that, so it's kinda an image LLM used for video. For all others I am trying to make two separate processors, for images and for videos, with their own special tokens

File: docs/source/en/tasks/video_text_to_text.md [hunk 10]
```diff
@@ -0,0 +1,145 @@
...
+</div>
+
+Now we can preprocess the inputs.
+
+This model has a prompt template that looks like following. First we'll put all sampled frames into one list. Since we have eight frames in each video, we will insert 12 `<image>` tokens to our prompt. Note that we are adding `assistant` at the end to trigger model to give answers. We can then preprocess.
+
+```python
+user_prompt = "Are these two cats in these two videos doing the same thing?"
+toks = "<image>" * 12
+prompt = "<|im_start|>user"+ toks + f"\n{user_prompt}<|im_end|><|im_start|>assistant"
```
[the remark this answers is not in the document]
Comment (merveenoyan) [reply docs/source/en/tasks/video_text_to_text.md:128]: what if a given model doesn't have a chat template?

[the remark this answers is not in the document]
Comment (zucchini-nlp) [reply docs/source/en/tasks/video_text_to_text.md:128]: Oh, right, there're still models without a template, Yeah, in that case I think the line below about existence of `chat_templates` is enough

**Comment by merveenoyan** [comment]
@zucchini-nlp re: slack discussions I'd say we merge this and edit when the processors are out.

**Review by zucchini-nlp — APPROVED** [review]
Yes, sounds good to me. We'll let users to discover how each model expects the inputs by model card, as there's no one standard yet and we don't support natively video-only LLMs

Approved, thanks! 💛
