### PR TITLE
Generate: support for left-padding on GPTNeoX and Llama

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

As the title indicates, adds left-padding support for GPTNeoX and Llama.

It adds the `position_ids` input, propagates all the way to the position embedding, and gathers the position embeddings given the value in `position_ids`. All slow tests are now passing in both models, including the newly added left-padding support test and the GPTNeoX integration test.

Also makes a few changes on Llama to make it more similar to other models 🤗

### CODE REVIEW

**Comment by gante** [comment]
The failing CI is fixed by #22383 :)

File: src/transformers/models/gptj/modeling_gptj.py
Comment (ArthurZucker) [inline src/transformers/models/gptj/modeling_gptj.py:1]: There doesn't seems to be changes to this file other than that should this be part of the PR?

File: tests/models/gpt_neox/test_modeling_gpt_neox.py [hunk 1]
```diff
@@ -237,7 +237,7 @@ def test_feed_forward_chunking(self):
 @require_torch
 class GPTNeoXLanguageGenerationTest(unittest.TestCase):
     @slow
-    def test_lm_generate_codegen(self):
+    def test_lm_generate_gptneox(self):
```
Comment (ArthurZucker) [inline tests/models/gpt_neox/test_modeling_gpt_neox.py:240]: nice catch

**Review by ArthurZucker — APPROVED** [review]
Works for me! I like the addition of the type hints 😉

**Review by sgugger — COMMENTED** [review]
Thanks for working on this. The change model->llama needs to be reverted as it will break all existing repos of Llama models on the Hub.

File: src/transformers/models/gptj/modeling_gptj.py
Comment (gante) [reply src/transformers/models/gptj/modeling_gptj.py:1]: Not necessarily -- it's a little typo (for which I probably wouldn't spend the time to open a PR 😅 )

**Comment by gante** [comment]
@ArthurZucker @sgugger woopsie, I forgot that it affected the weight loading code -- I come from a place where weight names have to be specified 👼 Reverted (`self.llama` is `self.model` again)!

**Review by sgugger — APPROVED** [review]

**Comment by jquesnelle** [comment]
It appears as if this may have broken FSDP. For example, as specified in the Alpaca repo, finetuning with `--fsdp "full_sh
ard auto_wrap" --fsdp_transformer_layer_cls_to_wrap LlamaDecoderLayer` worked before this commit, but after it gives the error such as:

```python
File "/home/fsuser/.local/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 313, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/fsuser/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'position_ids'
```

Reverting the commit fixes it, although perhaps the problem is with `accelerate` not supporting `position_ids`? cc: @ArthurZucker

**Comment by gante** [comment]
@jquesnelle can you paste the full stack trace? It would allow us to find the root cause :D (maybe, as you mention, the problem is in accelerate... or maybe it comes from the Alpaca repo!)

**Comment by neggert** [comment]
I'm seeing a pretty significant performance hit on RedPajama-7b-chat that I think is due to this change. I ran the PyTorch profiler and all of the `repeat` operators in `apply_rotary_pos_emb` are expensive and run mostly on CPU. Reverting to transformers 4.27.x resolves the performance issue.

**Comment by ArthurZucker** [comment]
You should try the `main` branch, #22785 removed the repeat solving this

**Comment by awgu** [comment]
@gante 

```
position_ids = attention_mask.long().cumsum(-1) - 1
position_ids.masked_fill_(attention_mask == 0, 1)
```
Could you explain why you fill `position_ids` to value 1 when `attention_mask == 0`? Why the value of 1?
