### ISSUE TITLE
PaliGemma2 doesn't work with transformers v4.48.2

### ISSUE THREAD

**Issue by koron** [huggingface/transformers#36029]
### System Info

- `transformers` version: 4.48.2
- Platform: Linux-6.12.8-200.fc41.x86_64-x86_64-with-glibc2.40
- Python version: 3.13.1
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.5.2
- Accelerate version: 1.3.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.4.0a0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no
- Using GPU in script?: yes
- GPU type: AMD Radeon RX 7600 XT

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Run [example script in PaliGemma2 model card](https://huggingface.co/google/paligemma2-3b-pt-224#use-in-transformers) with transfomers v4.48.2
2. It failed with `TypeError: PaliGemmaForConditionalGeneration.forward() got an unexpected keyword argument 'last_cache_position'. (snipped)`

If I try the same thing with transformers v4.48.1 it works.

### Expected behavior

It should be successful.

---

This PR https://github.com/huggingface/transformers/pull/35681 which is released as v4.48.2, introduced `last_cache_position` kwarg to Gemma2 model.

As a side effect of this, the same  `last_cache_position` kwarg may be passed to PaliGemma2.
But PaliGemma2 doesn't know `last_cache_position` kwarg, and [the example script in model card of PaliGemma2](https://huggingface.co/google/paligemma2-3b-pt-224#use-in-transformers) fails to run with the following error:

```
TypeError: PaliGemmaForConditionalGeneration.forward() got an unexpected keyword argument 'last_cache_position'. Did you mean 'cache_position'?
```

**Comment by zucchini-nlp** [comment]
Hey! Thanks for clear reproducer, indeed the paligemma should be adopted to the latest changes in LM backbone. Would you like to open a PR?

**Comment by koron** [comment]
Thanks @zucchini-nlp for the reply.

Sorry, but I'm not yet familiar enough with the transformers code to make a PR.

**Comment by zucchini-nlp** [comment]
Oke, no problem, I will fix it :)

**Comment by vkcorp** [comment]
FYI. It's still working with 4.47.1.

**Comment by ArthurZucker** [comment]
4.48.3 should have fixed it!
