### PR TITLE
Fix https://github.com/huggingface/transformers/issues/40292

### LINKED ISSUE #40292: transformers==4.55.2 still imports TFPreTrainedModel even with TRANSFORMERS_NO_TF=1"
### System Info

**Describe the bug**
When using transformers==4.55.2 with TensorFlow disabled (TRANSFORMERS_NO_TF=1), the library still attempts to import TFPreTrainedModel internally, causing an ImportError even though only PyTorch is being used.

**Environment info**
-> Python version: 3.13 (Windows 11, x86_64-pc-windows-msvc)
-> Transformers version: 4.55.2
-> Accelerate version: 1.10.0
-> Torch version: 2.5.0+cpu
-> TensorFlow: not installed (intentionally, since PyTorch is used)

**Error message**
ImportError: cannot import name 'TFPreTrainedModel' from 'transformers.modeling_tf_utils'

**Additional context**
This bug prevents PyTorch-only workflows from working with Transformers 4.55.2.
TensorFlow ≥2.16.1 is also not installable on Python 3.13, which makes this issue more severe.

**Related issue :**  This may be caused by a regression in recent refactoring of modeling_tf_utils imports.

**Suggested fix : ** Respect TRANSFORMERS_NO_TF=1 when importing, and avoid hard imports of TensorFlow modules if TF is disabled.

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install transformers==4.55.2 with PyTorch only (no TensorFlow).
2. Set environment variable:
               export TRANSFORMERS_NO_TF=1
(or set TRANSFORMERS_NO_TF=1 on Windows)
3. Run a script that only uses PyTorch models (e.g., Trainer with BertForSequenceClassification).

### Expected behavior

The library should not attempt to import TensorFlow components (TFPreTrainedModel) when TRANSFORMERS_NO_TF=1 is set, and no TensorFlow should be required.

### PR DESCRIPTION
**Pull request by id01**
# What does this PR do?

Fixes #40292
https://github.com/huggingface/transformers/issues/40292#issuecomment-3220768012

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

@Rocketknight1

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
Changes look good! Hold on, I'll see if I can get the CI green :dragon_face:

**Comment by Rocketknight1** [comment]
Merged, and thank you for the PR!
