### PR TITLE
Fix FA2 import + deprecation cycle 

### LINKED ISSUE #27319: ImportError: cannot import name 'is_flash_attn_available' from 'transformers.utils' (~/lib/python3.10/site-packages/transformers/utils/__init__.py)
### System Info

transformers: 4.35.0
python: 3.10.13
Platform: Linux

### Who can help?

@Narsil @ArthurZucker @SunMarc 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch
model = AutoModelForCausalLM.from_pretrained("01-ai/Yi-6B-200K", trust_remote_code=True,torch_dtype=torch.bfloat16, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained("01-ai/Yi-6B-200K",trust_remote_code=True)
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

This works fine with 4.34.1 transformers verion

### Expected behavior

The model gets loaded correctly

BUT I got this error: 

ImportError: cannot import name 'is_flash_attn_available' from 'transformers.utils' (~/lib/python3.10/site-packages/transformers/utils/__init__.py)

This works fine with 4.34.1 transformers verion

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ?

This PR puts back `is_flash_attn_available` and make it go through a deprecation cycle. It was removed in this [PR](#26785). As this method was never private, some remote modeling files used it. Fixes #27319

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Nice, thank you Marc!

File: src/transformers/utils/import_utils.py [hunk 1]
```diff
@@ -614,6 +614,14 @@ def is_flash_attn_2_available():
     return _flash_attn_2_available and torch.cuda.is_available()
 
 
+def is_flash_attn_available():
+    warnings.warn(
```
Comment (amyeroberts) [inline src/transformers/utils/import_utils.py:618]: We're trying to move towards using `logger` for warnings so that users have more control over the verbosity of their logs 

```suggestion
    logger.warning(
```

**Review by amyeroberts — APPROVED** [review]
Thanks for adding!

**Comment by amyeroberts** [comment]
@SunMarc Merging so this can be part of a patch release.
