### PR TITLE
Update checks for torch.distributed.tensor to require torch >= 2.5

### LINKED ISSUE #34795: Errors when using transformers with torch<2.5
### System Info

Transformers latest from `main`, pytorch 2.3, cpu or gpu.

Needs to have #34184

### Who can help?

@ArthurZucker @muellerzr 

### Information

- [x] My own modified scripts

### Reproduction

1. `pip install torch==2.3`
2. `pip install git+https://github.com/huggingface/transformers.git`
3. `python -c "import transformers.models.vision_encoder_decoder.modeling_vision_encoder_decoder"`

### Expected behavior

This does not error out with torch 2.5, but does with torch 2.3 or 2.4, if these are not supported, we should get an error message when installing transformers.

### PR DESCRIPTION
**Pull request by loadams**
# What does this PR do?

Supplements #34800, the checks for torch.distributed.tensor require torch >= 2.5 as the comment states, this adds the check for it and updates the check.

Fixes #34795

## Who can review?

@ArthurZucker @muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for catching 🤗

**Comment by pglorio** [comment]
Thanks for this! I tried these fixes but I ran into this error:
```
ImportError: cannot import name 'Replicate' from 'torch.distributed.tensor' (/usr/local/lib/python3.10/dist-packages/torch/distributed/tensor/__init__.py)
```
when using torch 2.5.0, which was issued from [this line](https://github.com/huggingface/transformers/blob/e1f6ff7d9183e45246d08e07703465a9210191b0/src/transformers/pytorch_utils.py#L44). I was able to make it work with torch 2.5.1.

**Review by ArthurZucker — COMMENTED** [review]
Thanks, let's rather use `is_torch_greater_or_equal("2.5")` from https://github.com/huggingface/transformers/blob/6aba68c0b9508b8c8fce025bd5492151258cd57a/src/transformers/utils/import_utils.py#L932-L938 And good to go!

**Review by SunMarc — APPROVED** [review]
LGTM ! I reran the tests. These are unrelated to the PR

**Comment by ArthurZucker** [comment]
THanks, merging!
