### ISSUE TITLE
AutoModelForImageClassification broken in 4.52.4: AttributeError: 'TinyVit' object has no attribute '_initialize_weights'

### ISSUE THREAD

**Issue by virgile-fsr** [huggingface/transformers#38996]
### System Info

Hello, here is a snippet of code that leads to an error with transformers 4.52.4, but worked fine with 4.48.3.

```
from transformers import AutoModelForImageClassification, AutoConfig

pretrained_model="timm/tiny_vit_21m_512.dist_in22k_ft_in1k"
config = AutoConfig.from_pretrained(pretrained_model)
config.num_labels = 1
config.num_channels = 4
self.model = AutoModelForImageClassification.from_pretrained(pretrained_model, config=config, ignore_mismatched_sizes=True)

```         

Error:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 309, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4574, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4884, in _load_pretrained_model
    model._initialize_missing_keys(checkpoint_keys, ignore_mismatched_sizes, is_quantized)
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 5477, in _initialize_missing_keys
    self.initialize_weights()
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 2556, in initialize_weights
    self.smart_apply(self._initialize_weights)
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/transformers/modeling_utils.py", line 2547, in smart_apply
    module.smart_apply(module._initialize_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mvc-cpu/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1940, in __getattr__
    raise AttributeError(
AttributeError: 'TinyVit' object has no attribute '_initialize_weights'
```

### Who can help?

@amyeroberts  @qubvel 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoModelForImageClassification, AutoConfig

pretrained_model="timm/tiny_vit_21m_512.dist_in22k_ft_in1k"
config = AutoConfig.from_pretrained(pretrained_model)
config.num_labels = 1
config.num_channels = 4
self.model = AutoModelForImageClassification.from_pretrained(pretrained_model, config=config, ignore_mismatched_sizes=True)

```         

### Expected behavior

In 4.48.3, the model is correctly initialized with a simple warning for newly initialized weight, which is the expected behavior.
```
Some weights of TimmWrapperForImageClassification were not initialized from the model checkpoint at timm/tiny_vit_21m_512.dist_in22k_ft_in1k and are newly initialized because the shapes did not match:
- head.fc.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([1]) in the model instantiated
- head.fc.weight: found shape torch.Size([1000, 576]) in the checkpoint and torch.Size([1, 576]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by NielsRogge** [comment]
Hi,

I'm not able to reproduce this (I have a dev install of Transformers), here's what I get on the main branch:

```bash
config.json: 100%|███████████████████████████████████████████████████████| 599/599 [00:00<00:00, 1.15MB/s]
model.safetensors: 100%|█████████████████████████████████████████████| 85.2M/85.2M [00:02<00:00, 37.1MB/s]
Some weights of TimmWrapperForImageClassification were not initialized from the model checkpoint at timm/tiny_vit_21m_512.dist_in22k_ft_in1k and are newly initialized because the shapes did not match:
- timm_model.head.fc.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([1]) in the model instantiated
- timm_model.head.fc.weight: found shape torch.Size([1000, 576]) in the checkpoint and torch.Size([1, 576]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

**Comment by virgile-fsr** [comment]
Hi,

I have tried to narrow the version change:
- up to `4.51.3`, it works
- from `4.52.0` onward I get the error above

The rest of the environment is unchanged, I simply do `pip install transformers==4.52.0` to change the installed version of transformers. I have tried on both macOS and Ubuntu.

**Comment by qubvel** [comment]
Hi @virgile-fsr, the provided code also works for me on the `main` branch (no issues). Can you check if updating transformers helps you?

```
pip install -U git+https://github.com/huggingface/transformers
```

**Comment by virgile-fsr** [comment]
Thanks, this worked. It installs `transformers-4.53.0.dev0`.
`pip install transformers --upgrade` only installs up to 4.52.4 which has the bug, so I didn't try the dev version before.

**Comment by qubvel** [comment]
Ok, great! Thanks for reporting and updating to the latest version 🤗 we should have a PyPI release soon, so you will be able to install from there
