### PR TITLE
Fix continuous batching for multimodal models

### LINKED ISSUE #44423: [Bug] `transformers serve --continuous-batching` crashes with multimodal models (Qwen3.5) — AttributeError: 'str' object has no attribute 'to'
### System Info

- `transformers` main branch (5.3.0.dev0, commit 5c1c72be)
- Python 3.11.14
- PyTorch 2.5.1+cu121
- OS: Ubuntu Linux

### Who can help?

@Lysandre @ArthurZucker @joaogante

### Reproduction

1. Install latest transformers from main:
```bash
pip install "transformers[serving] @ git+https://github.com/huggingface/transformers.git@main"
```

2. Launch the server with continuous batching:
```
transformers serve --force-model Qwen/Qwen3.5-9B --port 8000 --continuous-batching
```

3. Send any chat completion request:
```
curl -X POST http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{"model": "Qwen/Qwen3.5-9B", "messages": [{"role": "user", "content": "Hello"}]}'
```

### Error
```
File "transformers/cli/serve.py", line 831, in continuous_batching_chat_completion
    ).to(model.device)["input_ids"][0]
      ^^
AttributeError: 'str' object has no attribute 'to'
```

### Root Cause
In [serve.py line 829-831](https://github.com/huggingface/transformers/blob/main/src/transformers/cli/serve.py#L829-L831):
```
inputs = processor.apply_chat_template(
    req["messages"], return_tensors="pt", add_generation_prompt=True, return_dict=True
).to(model.device)["input_ids"][0]
```

For multimodal models like Qwen3.5, `processor` is a multimodal processor (not a plain tokenizer). Its `apply_chat_template()` returns a plain string instead of a `BatchEncoding`, so calling `.to(model.device)` raises `AttributeError.`

Note: Without `--continuous-batching`, the server works fine with Qwen3.5.

### Expected behavior

`transformers serve --continuous-batching` should handle multimodal models whose processor returns a string from `apply_chat_template`.

### PR DESCRIPTION
**Pull request by jw9603**
Fixes #44423

`continuous_batching_chat_completion` was missing input preprocessing and `tokenize=True` in `apply_chat_template`, causing `'str' object has no attribute 'to'` for multimodal models.

Added the same `get_model_modality` + `get_processor_inputs_from_inbound_messages` preprocessing already used in `generate_chat_completion`.

### CODE REVIEW

File: tests/cli/test_serve.py [hunk 1]
```diff
@@ -480,6 +480,27 @@ def test_processor_inputs_from_inbound_messages_vlm_text_and_image_in_base_64(se
             else:
                 raise ValueError("VLMs should only receive content as lists.")
 
+    def test_apply_chat_template_tokenize_for_vlm(self):
+        from transformers import AutoProcessor
+
+        processor = AutoProcessor.from_pretrained("HuggingFaceTB/SmolVLM-Instruct")
+
+        messages = [{"role": "user", "content": "Hello"}]
```
Comment (zucchini-nlp) [inline tests/cli/test_serve.py]: The fix looks good to me. Regarding tests, prob we need a test for cont batching specifically as in 
https://github.com/huggingface/transformers/blob/fd6bc380c8854a370fbc9f68a157895d84dce7d7/tests/cli/test_serve.py#L639-L651

cc @remi-or for confirmation and review

Comment (remi-or) [reply tests/cli/test_serve.py]: No need to add a test for continuous batching and VLMs yet, because continuous batching only support text-only models!

File: src/transformers/cli/serve.py [hunk 2]
```diff
@@ -829,8 +829,11 @@ def continuous_batching_chat_completion(self, req: dict, request_id: str) -> Str
             self.running_continuous_batching_manager.start()
 
         # TODO (Joao, Lysandre): this should also work with tool support
+        modality = self.get_model_modality(model, processor=processor)
```
Comment (remi-or) [inline src/transformers/cli/serve.py]: Since we only support text-only models, it would make sense for this to do this check before we launch continuous batching, and switch to regular generate if the model is not text only.

File: tests/cli/test_serve.py [hunk 3]
```diff
@@ -663,6 +684,27 @@ def test_full_request(self):
             )
         )
 
+    def test_full_request_vlm(self):
```
Comment (remi-or) [inline tests/cli/test_serve.py]: No need for this test, this should not work.

**Comment by jw9603** [comment]
Thanks for the review! 

Should I add the modality check in chat_completion before routing to continuous_batching_chat_completion, so that VLMs fall back to generate_chat_completion?

**Comment by remi-or** [comment]
> Thanks for the review!
> 
> Should I add the modality check in chat_completion before routing to continuous_batching_chat_completion, so that VLMs fall back to generate_chat_completion?

Probably, and also throw a warning about this.

**Comment by jw9603** [comment]
> > Thanks for the review!
> > Should I add the modality check in chat_completion before routing to continuous_batching_chat_completion, so that VLMs fall back to generate_chat_completion?
> 
> Probably, and also throw a warning about this.

Done, added a `warning_once` for the fallback. Thanks!

**Review by remi-or — APPROVED** [review]
LGTM! Thanks for the contribtion
