### PR TITLE
Fix `kernelize()` crash for gpt_oss: missing `@use_kernel_func_from_hub` on `apply_rotary_pos_emb`

### PR DESCRIPTION
**Pull request by jiqing-feng**
## Problem

PR #45420 refactored kernel function registration to use a hidden `_hidden_kernels` dict + temporary `register_module` attach/detach cycle. This works correctly when the target function is decorated with `@use_kernel_func_from_hub` (which wraps it into an `nn.Module` instance via `_create_func_module`).

However, `gpt_oss` uses `@use_kernelized_func(apply_rotary_pos_emb)` where `apply_rotary_pos_emb` is a **plain function** — missing the `@use_kernel_func_from_hub("rotary_pos_emb")` decorator that other models (deepseek_v3, gemma3, etc.) have. This causes:

1. `register_module` raises `TypeError: ... is not a Module subclass`
2. In the `finally` block, `delattr` raises `AttributeError` since attach never succeeded

## Fix

1. **`modeling_gpt_oss.py`**: Add `@use_kernel_func_from_hub("rotary_pos_emb")` decorator to `apply_rotary_pos_emb`, consistent with all other models.
2. **`modeling_utils.py`**: Make `attach_hidden_kernels` defensive — skip non-`nn.Module` entries with a warning instead of crashing. Use safe `_modules` dict access for detach.

## Reproduce

```python
from transformers import pipeline
generator = pipeline('text-generation', model='openai/gpt-oss-20b', model_kwargs={'use_kernels': True})
```

error:
```
......
  File "/opt/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1077, in apply
    fn(self)
  File "/home/jiqing/transformers/src/transformers/modeling_utils.py", line 4581, in detach_hidden_kernels
    delattr(module, name)
  File "/opt/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2086, in __delattr__
    super().__delattr__(name)
AttributeError: 'GptOssAttention' object has no attribute 'apply_rotary_pos_emb'
```

## Regression

Introduced in #45420 (commit 253809c97d).

### CODE REVIEW

**Comment by jiqing-feng** [comment]
Hi @vasqu . Would you please review this PR? Thanks!

File: src/transformers/models/gpt_oss/modular_gpt_oss.py [hunk 1]
```diff
@@ -171,6 +171,7 @@ def _apply_rotary_emb(
     return torch.cat((first_, second_), dim=-1)
 
 
+@use_kernel_func_from_hub("rotary_pos_emb")
```
Comment (vasqu) [inline src/transformers/models/gpt_oss/modular_gpt_oss.py:174]: Fair point thanks for spotting! Imo, the formula is the same not sure why it was not copied from llama but not too important

File: src/transformers/modeling_utils.py [hunk 2]
```diff
@@ -4574,11 +4574,18 @@ def kernelize(self, mode=None):
...
             for name, fn in getattr(module, "_hidden_kernels", {}).items():
                 if name not in dict(module.named_children()):
-                    module.register_module(name, fn)
+                    if isinstance(fn, torch.nn.Module):
+                        module._modules[name] = fn
+                    else:
+                        logger.warning_once(
+                            f"Skipping kernel registration for '{name}': not an nn.Module. "
+                            f"Consider decorating it with @use_kernel_func_from_hub."
+                        )
```
Comment (vasqu) [inline src/transformers/modeling_utils.py]: Any reason you needed this? Imo, the isinstance check is fair but I would avoid using `_modules` directly and revert to the old native style (below as well)

**Review by vasqu — APPROVED** [review]
Can you add a regression test for gpt oss that runs with kernels --> just that it does not crash

File: src/transformers/modeling_utils.py (hunk 2 above)
Comment (jiqing-feng) [reply src/transformers/modeling_utils.py]: done.

**Comment by jiqing-feng** [comment]
Hi @vasqu . I have fixed the comment and added the test, please review it. Thanks!

**Comment by jiqing-feng** [comment]
The failed CI is not related to my changes.

**Review by vasqu — APPROVED** [review]
Thanks, I just changed it to raise an ValueError at the end instead. Having a broken registry shouldn't be the case and silently warning will be ignored so I'd rather be more strict here
