### ISSUE TITLE
Error while fine-tuning model for GPT2

### ISSUE THREAD

**Issue by dasavisha** [huggingface/transformers#1484]
## 🐛 Bug

Model I am using GPT2:

Language I am using the model on English:

The problem arise when using:
* [ ] the official example scripts: I run the run_lm_finetuning.py script from the examples folder

The tasks I am working on is:
* [ ] my own task or dataset: The WritingPrompts dataset.

## To Reproduce

1. Running the run_lm_generation.py on the WP dataset. 
 python run_lm_finetuning.py --output_dir=output_ft_gpt2 --model_type=gpt2 --model_name_or_path=gpt2 --do_train --train_data_file=../stories_data/writingPrompts/train.wp_target --do_eval --eval_data_file=../stories_data/writingPrompts/test.wp_target --block_size=128 --save_total_limit=100

Error: Traceback (most recent call last):
  File "run_lm_finetuning.py", line 538, in <module>
    main()
  File "run_lm_finetuning.py", line 485, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False)
  File "run_lm_finetuning.py", line 97, in load_and_cache_examples
    dataset = TextDataset(tokenizer, file_path=args.eval_data_file if evaluate else args.train_data_file, block_size=args.block_size)
  File "run_lm_finetuning.py", line 80, in __init__
    self.examples.append(tokenizer.build_inputs_with_special_tokens(tokenized_text[i:i+block_size]))
AttributeError: 'GPT2Tokenizer' object has no attribute 'build_inputs_with_special_tokens'

**Comment by LysandreJik** [comment]
Hi! It seems like you have taken the example from the latest version but that youŕe library is not up to date. Could you tell me the version of your `transformers` library ?

**Comment by dasavisha** [comment]
Hi! 
I am using the version 2.0.0.

**Comment by LysandreJik** [comment]
If you´re using the version 2.0.0 you should use the [script that was used in this version](https://github.com/huggingface/transformers/blob/v2.0.0/examples/run_lm_finetuning.py). The current script works on version 2.1!

**Comment by dasavisha** [comment]
Thanks!
