### PR TITLE
Fix gemma4 video to device

### LINKED ISSUE #47879: Error during video handling with Gemma4 (E2B-Instruct)
### System Info

- `transformers` version: 5.15.0.dev0
- Platform: Linux-6.18.33.1-microsoft-standard-WSL2-x86_64-with-glibc2.43
- Python version: 3.13.14
- Huggingface_hub version: 1.24.0
- Safetensors version: 0.8.0
- Accelerate version: 1.14.0
- Accelerate config:    not found
- DeepSpeed version: not installed
- PyTorch version (accelerator?): 2.13.0+cu132 (CUDA)
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: Not clear.
- GPU type: NVIDIA GeForce RTX 4080 Laptop GPU

### Who can help?

@molbap @guarin

The issue is with the vision model (Gemma4-E2B-IT)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
File ".../transformers/models/gemma4/modeling_gemma4.py", line 2344, in forward
video_features = video_features.to(inputs_embeds.device, inputs_embeds.dtype)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'to'
```

The error is resolved on changing the code to:
```
video_features = video_features[0].to(inputs_embeds.device, inputs_embeds.dtype)
```

### Expected behavior

The code works well by making the aforementioned change (which should be default behaviour).

### PR DESCRIPTION
**Pull request by guarin**
[CI](https://transformers-ci.lor-e.huggingface.cool/d/pytest-observability-by-pr/pytest-observability-branch?var-pr=47896)

# What does this PR do?

Fixes `video_features.to(device)` which failed because `video_features` is now a tuple and not a tensor (since https://github.com/huggingface/transformers/pull/46405).

I also aligned gemma4 unified to follow the new the new shapes for image and video features.

@zucchini-nlp I noticed that diffusion gemma doesn't follow the expected shapes either but didn't change it as https://github.com/huggingface/transformers/pull/46405 explicitly added it that way. 

Fixes https://github.com/huggingface/transformers/issues/47879

### CODE REVIEW

**Comment by guarin** [comment]
run-slow: gemma4, gemma4_unified

File: src/transformers/models/gemma4_unified/modular_gemma4_unified.py [hunk 1]
```diff
@@ -965,12 +966,18 @@ def get_video_features(
         video_position_ids (`torch.LongTensor` of shape `(num_videos, num_frames, max_patches, 2)`, *optional*):
             2D patch position coordinates from the video processor, with `(-1, -1)` indicating padding.
         """
-        # Flatten video frames: (num_videos, num_frames, ...) → (num_videos*num_frames, ...)
```
Comment (zucchini-nlp) [inline src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: hmm i wonder how the tests didn't complain about this, we have `test_get_image_features_output` 🤔

**Review by zucchini-nlp — APPROVED** [review]
Looks good, though it's weird tests didn't complain. Can you check if they are running for gemma4?

**Comment by zucchini-nlp** [comment]
We defi need proper video model tests, I am working on it and will put higher prio

File: src/transformers/models/gemma4_unified/modular_gemma4_unified.py (hunk 1 above)
Comment (guarin) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: I think it is because the video tester is missing

Comment (zucchini-nlp) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: You also fixed `get_image_feeatures` no?

Comment (guarin) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: Ah sorry i thought this was about normal gemma4. Hmm there is this:

https://github.com/huggingface/transformers/blob/c7e57f79348480f73d3ef0ad8c47f807ef1378c8/tests/models/gemma4_unified/test_modeling_gemma4_unified.py#L398-L414

Maybe I missed something and this doesn't make sense. Will double check.

Comment (zucchini-nlp) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: wow, a lot to skip though it makes sense for attn/hidden states. The `test_get_image_features_output` iirc doesn't require anything but it's not on you, maybe we indeed need to refine the tests a bit instead of skipping

Comment (guarin) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: Yeah `test_get_image_features_output` expects the usual output attributes to exist:

https://github.com/huggingface/transformers/blob/c7e57f79348480f73d3ef0ad8c47f807ef1378c8/tests/test_modeling_common.py#L5228-L5240

Comment (zucchini-nlp) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: oke, thanks, I will split it more clearly then. Skipping tests isn't good

Comment (molbap) [reply src/transformers/models/gemma4_unified/modular_gemma4_unified.py:968]: arg yes, good catch

**Comment by guarin** [comment]
@Cyrilvallez if you have time for a review :)

**Comment by zucchini-nlp** [comment]
I think we can merge since it was just left-out from prev PR, no new features. Maybe also has to go in patch release
