### ISSUE TITLE
Error: StaticCache.__init__() got an unexpected keyword argument 'batch_size'

### ISSUE THREAD

**Issue by rsxdalv** [huggingface/transformers#38914]
Upgrading transformers breaks the 'new' name and instead reverts back to the 'deprecated' name...

```
  Attempting uninstall: transformers
    Found existing installation: transformers 4.46.1
    Uninstalling transformers-4.46.1:
      Successfully uninstalled transformers-4.46.1
Successfully installed tokenizers-0.21.1 transformers-4.52.4
```

Code went from:
```
    def __init__(
        self,
        config: PretrainedConfig,
        batch_size: int = None,
        max_cache_len: int = None,
        device: torch.device = None,
        dtype: torch.dtype = torch.float32,
        max_batch_size: Optional[int] = None,
        layer_device_map: Optional[Dict[int, Union[str, torch.device, int]]] = None,
    ) -> None:
        super().__init__()
        if max_batch_size is not None:
            logger.warning_once(
                f"The 'max_batch_size' argument of {self.__class__.__name__} is deprecated and will be removed in "
                "v4.46. Use the more precisely named 'batch_size' argument instead."
            )

        self.batch_size = batch_size or max_batch_size
        self.max_cache_len = config.max_position_embeddings if max_cache_len is None else max_cache_len
```

to
```
    def __init__(
        self,
        config: PretrainedConfig,
        max_batch_size: int,
        max_cache_len: Optional[int] = None,
        device: Union[torch.device, str, None] = None,
        dtype: torch.dtype = torch.float32,
        layer_device_map: Optional[Dict[int, Union[str, torch.device, int]]] = None,
    ) -> None:
        super().__init__()
        self.max_batch_size = max_batch_size
        self.max_cache_len = config.max_position_embeddings if max_cache_len is None else max_cache_len
```

Edit: 
One more: 
`Error: 'StaticCache' object has no attribute 'dtype'`

**Comment by sandeepyadav1478** [comment]
Hey @rsxdalv ,

May I know, what exactly we want to achieve here? As we can update code-base to use  `batch_size` -> `max_batch_size`.
Often version changes also gets update related to variables & keywords... :-)

**Comment by rsxdalv** [comment]
@sandeepyadav1478 We're trying to have some consistency with an API, semver and deprecation. You build your code to work with transformers==4.46.1, but it tells you, repeatedly, that you should be using 'batch_size' as 'max_batch_size' is deprecated, and let's use _precise naming_. So you do that, then turns out that when you try to use a newer version, transformers==4.52.4 (not breaking change upgrade, according to semver) has completely removed the 'new' version and instead reverted back to the deprecated version.
The likely outcome of that is pinning transformers to 1 version. Then you get another project pinning it to another version, which later results in a dependency conflict. That leads to refactoring the breaking dependencies out of projects.

**Comment by sandeepyadav1478** [comment]
@rsxdalv I totally understand your use case & frustration. Of these version updates, We also face similar issue at my currently working company projects. We tend to follow these steps based on conditions
- few of dependencies we update rarely (which is not related to major operations), then we do code refactoring as you suggested.
- few dependencies needs to updates asap (used in major operations or brings security updates) then we use a wrapper/abstraction class which acts as middleman (we call it Sync files locally) these are version specific classes.

Take this for example:
```py
class NotifierBase:
    def notify(self, user_id, message):
        """Send a notification to a user. To be implemented by subclasses."""
        raise NotImplementedError("Subclasses must implement this method")

class NotifierV1.0(NotifierBase):
    def __init__(self, third_party_notifier):
        self.third_party_notifier = third_party_notifier

    def notify(self, user_id, message):
        # Map to dependency's parameter names
        self.third_party_notifier.send_notification(user=user_id, msg=message)

class NotifierV2.0(NotifierBase):
    def __init__(self, third_party_notifier):
        self.third_party_notifier = third_party_notifier

    def notify(self, user_id, message):
        # Map to new dependency's parameter names
        self.third_party_notifier.send_notification(recipient=user_id, message=message)
```
*Both child classes accepts same parameters and then pass em to their version specific parameters*

I have seen it too often with multiple projects, it helps in faster hotfix deployments and custom requirements for any specific user/entity.

> __I know, it can we overhead to implement it but for major dependencies it's best practice to use abstraction. Seen as must condition mostly.__

I hope I was able to help you. :-)
Lmk, if you have any more questions!

**Comment by sandeepyadav1478** [comment]
@rsxdalv I think, I had provided resolution to perform at your end for now in previous comment.
Let me raise a MR for the fixes you suggested. It might take time

**Comment by Rocketknight1** [comment]
cc @gante

**Comment by sandeepyadav1478** [comment]
Hello @gante 👋 ,

Should I work on creating MR as mentioned in previous comment?
Lmk, If I can pick it?

Thanks

**Comment by rsxdalv** [comment]
.

**Comment by rsxdalv** [comment]
Nice

**Comment by gante** [comment]
Hey @rsxdalv 👋 

I'm sorry. I have more notifications than I can handle, and I operate in a FIFO queue 😅 I understand your frustration at seeing your issue go unnoticed.

Do you know if the issue still persists on new versions? KV Caches went through a very rapid expansion of complexity over the last year, and we've finally hit a design we believe will remain stable. This design has landed in v4.54.

**Comment by rsxdalv** [comment]
Understandable, the github bot settings are a bit aggressive for this situation.
I now have code to suppress the warnings properly and not have them interact with torch.compile or show up to users who won't understand that these warnings are completely impossible to avoid. The new version seems to be using max_batch_size, although batch_size is also used throughout cache_utils.py.
