### PR TITLE
Use `math.pi` instead of `torch.pi` in `MaskFormer`

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

`MaskFormer` uses `torch.pi` which is only available in `torch >= 1.10`. The Past CI with PyTorch 1.9 gives
```bash
AttributeError: module 'torch' has no attribute 'pi'
``` 
This PR adds a warning if PT <= 1.9 for this model, similar in `ViltModel` https://github.com/huggingface/transformers/blob/71fc33174664738d8c8d93025ebc810180e69c20/src/transformers/models/vilt/modeling_vilt.py#L44

**Question: Should we also skip the whole test suite for  `MaskFormer` depending on the torch version? The objective is to make Past CI cleaner if we ever run it again with previous torch version.**

### CODE REVIEW

File: src/transformers/models/maskformer/modeling_maskformer.py [hunk 1]
```diff
@@ -50,6 +50,11 @@
 
 logger = logging.get_logger(__name__)
 
+if not is_torch_greater_or_equal_than_1_10:
+    logger.warning(
+        f"You are using torch=={torch.__version__}, but torch>=1.10.0 is required to use "
+        "MaskFormerModel. Please upgrade torch."
+    )
```
Comment (ydshieh) [inline src/transformers/models/maskformer/modeling_maskformer.py:57]: We could probably use `torch.tensor(np.pi)` instead of `torch.pi` at https://github.com/huggingface/transformers/blob/c3b42a6f99766e6df051a19f81ca589a2511d71e/src/transformers/models/maskformer/modeling_maskformer.py#L2110

if we want to support as much PT versions as possible.

(But the Past CI for this model have to be re-run in order to get updated results).

**Review by sgugger — COMMENTED** [review]
If it's just for `torch.pi` can we change this to `math.pi` and have the model work with PyTorch 1.9?

**Review by sgugger — APPROVED** [review]
If it passes all tests, good for me!

**Review by LysandreJik — APPROVED** [review]
