### ISSUE TITLE
transformers 4.50 does not work with pytorch 2.0

### ISSUE THREAD

**Issue by koen-dejonghe** [huggingface/transformers#37238]
### System Info

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

results in 

```
RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
module 'torch' has no attribute 'compiler'
```

I cannot run `transformers-cli env` for the same reason.

transformers 4.49 does not have this issue.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

### Expected behavior

it should not give an error.

transformers 4.49 does not have this issue.

**Comment by purusharthmalik** [comment]
Is there a specific reason you are using `torch==2.0.1`?

**Comment by koen-dejonghe** [comment]
yes.
I need it to be compatible with faiss-gpu-cu11.

**Comment by koen-dejonghe** [comment]
duplicate of #37137

**Comment by Rocketknight1** [comment]
Yes - the latest versions of Transformers do not support versions of Torch lower than 2.1. We didn't update our requirements correctly, but we're fixing that in #37137
