### ISSUE TITLE
cannot import get_full_repo_name from huggingface_hub after updating pytorch

### ISSUE THREAD

**Issue by junchen14** [huggingface/transformers#31728]
### System Info

after I upgrade the pytorch from 2.0.0 to the above version such as 2.2.0, I could not properly import  'get_full_repo_name' from 'huggingface_hub'. 

from huggingface_hub import get_full_repo_name  # for backward compatibility
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'

any ideas about the reason?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

step1: upgrading pytorch to torch==2.2.0
step2: pip install transformers

open python interpreter in the terminal:
from huggingface_hub import get_full_repo_name

### Expected behavior

ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub'

**Comment by amyeroberts** [comment]
Hi @junchen14, thanks for reporting this issue! 

Could you: 
* Share the full error traceback? 
* Share the version of transformers, torch and huggingface_hub in your environment? 

```py
import transformers, huggingface_hub, torch

print(transformers.__version__)
print(huggingface_hub.__version__)
print(torch.__version__)
```

**Comment by SophonTec** [comment]
Similar ImportError:
ImportError: cannot import name 'get_full_repo_name' from 'huggingface_hub' (/home/sophon/.local/lib/python3.11/site-packages/huggingface_hub/__init__.py)

Name: transformers
Version: 4.42.3
Name: torch
Version: 2.3.1
Name: huggingface-hub
Version: 0.23.4

**Comment by LysandreJik** [comment]
Hey @SophonTec, this seems to point towards an error in your environment; the `get_full_repo_name` method is indeed present in `huggingface_hub`, see:

```py
>>> from huggingface_hub import __version__
>>> __version__
'0.23.0.dev0'
>>> from huggingface_hub import get_full_repo_name
>>>
```

Is it possible you have a `huggingface_hub` folder in your environment?

**Comment by jiangzongjie** [comment]
@junchen14  I also met the same  problem yesterday. I suggest you try the following step，and see if it can solve your  problem：
1. conda create -n qwen1.5 python=3.11
2. conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia
3. python -m pip install --upgrade pip
4. pip install packaging
5. pip install transformers
6. pip install accelerate
7. pip install sentencepiece
  holp it can work

**Comment by jiangzongjie** [comment]
@SophonTec I also met the same problem yesterday. I suggest you try the following step，and see if it can solve your problem：

conda create -n qwen1.5 python=3.11
conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia
python -m pip install --upgrade pip
pip install packaging
pip install transformers
pip install accelerate
pip install sentencepiece
holp it can work

**Comment by junchen14** [comment]
I fixed the problem by upgrading the package: charset-normalizer
