### ISSUE TITLE
GPT-OSS mxfp4 with triton_kernel: make_default_matmul_mxfp4_w_layout not found

### ISSUE THREAD

**Issue by yilian49** [huggingface/transformers#39945]
### System Info

- `transformers` version: 4.55.0
- Platform: Linux-5.15.0-144-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.34.3
- Safetensors version: 0.5.3
- Accelerate version: 1.9.0
- Accelerate config:    not found
- DeepSpeed version: not installed
- PyTorch version (accelerator?): 2.7.1+cu126 (CUDA)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA H100 80GB HBM3

### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tried to run the openai gpt-oss-120B model in mxfp4 on H100, following this setup command instruction as given by [this link](https://cookbook.openai.com/articles/gpt-oss/run-transformers#:~:text=pip%20install%20%2DU%20transformers%20accelerate%20torch%20triton%20kernels%0Bpip%20install%20git%2Bhttps%3A//github.com/triton%2Dlang/triton.git%40main%23subdirectory%3Dpython/triton_kernels)
`pip install -U transformers accelerate torch triton kernelspip install git+https://github.com/triton-lang/triton.git@main#subdirectory=python/triton_kernels`

I ran the script [provided here](https://cookbook.openai.com/articles/gpt-oss/run-transformers#:~:text=from%20transformers%20import%20AutoModelForCausalLM,decode(outputs%5B0%5D)))

(And I had to manually upgrade triton to 3.4.0)

The error message states:
`raceback (most recent call last):
  File "/workspace/projects/gpt_oss/generate.py", line 6, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 600, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 316, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5061, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5524, in _load_pretrained_model
    _error_msgs, disk_offload_index, cpu_offload_index = load_shard_file(args)
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 974, in load_shard_file
    disk_offload_index, cpu_offload_index = _load_state_dict_into_meta_model(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 882, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/quantizers/quantizer_mxfp4.py", line 223, in create_quantized_param
    load_and_swizzle_mxfp4(
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/integrations/mxfp4.py", line 375, in load_and_swizzle_mxfp4
    triton_weight_tensor, weight_scale = swizzle_mxfp4(
                                         ^^^^^^^^^^^^^^
  File "/workspace/projects/trainnew/lib/python3.11/site-packages/transformers/integrations/mxfp4.py", line 64, in swizzle_mxfp4
    value_layout, value_layout_opts = layout.make_default_matmul_mxfp4_w_layout(mx_axis=1)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'triton_kernels.tensor_details.layout' has no attribute 'make_default_matmul_mxfp4_w_layout'`

### Expected behavior

Expect the model to load and run

**Comment by Rocketknight1** [comment]
hi @yillian49, can you try installing transformers from `main`, just in case that makes a difference? if not cc @arthurzucker whenever he gets back

**Comment by yilian49** [comment]
> hi @yillian49, can you try installing transformers from `main`, just in case that makes a difference? if not cc [@ArthurZucker](https://github.com/ArthurZucker) whenever he gets back

I tried building from source from main, but the triton version it builds with is 3.3.1, and the mxfp4 support requires 3.4.0. So I then manually installed triton 3.4.0. Still the. same error.

**Comment by itsaphel** [comment]
I think the instructions in OpenAI's cookbook no longer work due to this commit: https://github.com/triton-lang/triton/commit/b3e9fadea14e708813028ee180a89c1162ec7074#diff-64bdf9d5616e0eb14a271234111457f6e1ea0292ebb012b6209b5857edb84040R6

Now, installing `triton_kernels` from the repo will try import `triton.tools.ragged_tma` which isn't available in `triton==3.4.0`

I guess you either need to install triton from git (I tried briefly, compilation was slow and it blew my RAM limit of 80GB so my job died with OOM), or install `triton_kernels` from [the parent commit](https://github.com/triton-lang/triton/commit/05b2c186c1b6c9a08375389d5efe9cb4c401c075) rather than main, until triton releases a new stable build.

**Comment by ArthurZucker** [comment]
I think we removed the restriction in latest `transformers` release to use the kernels on the hub!

**Comment by ArthurZucker** [comment]
cc @MekkCyber

**Comment by MekkCyber** [comment]
Hi @itsaphel, as Arthur mentionned, since `triton_kernels` are not released as a package with specific versions, It would be hard to keep track of the breaking changes, that's why we ported all kernels to the hub and and the integration is already merged in `main`, so now if you have `triton==3.4.0` and the package `kernels` installed you should be able to run inference with the quantized model

**Comment by ai-guy-7** [comment]
Hi @ArthurZucker @MekkCyber is there a solution for getting gpt-oss-120b/gpt-oss-20b working locally/offline, given that transformers now reaches out to HF for the kernels? I have `triton_kernels` installed locally (via the instructions given previously about downloading from git) but am getting `LocalEntryNotFound` errors re: transformers trying to reach out to HF to get the kernels. (Trying to run offline, and `HF_HUB_OFFLINE` set to 1).

**Comment by ArthurZucker** [comment]
Can you share a small reproducer ? Should not be the case!

**Comment by ai-guy-7** [comment]
Thank you so much for your help!! @ArthurZucker here you go, and let me know if you need any other details.

Some environment details:
Running on a NVIDIA H100
Python 3.10.12
`openai/gpt-oss-120b` pulled into local directory, at `/path/to/my/local/gpt-oss-120b`. Haven't run inference on it yet even in on-line mode (not sure if that makes a difference for the purpose of caching).
transformers==4.55.1
accelerate==1.10.0
torch==2.8.0
triton==3.4.0
kernels==0.9.0
triton_kernels==1.0.0 (via pip install git+https://github.com/triton-lang/triton.git@main#subdirectory=python/triton_kernels as that repo existed on Aug. 12 - this commit here: https://github.com/triton-lang/triton/commit/48d46bbc0b7a9fc4201e4f6ea36432b033d22c9e)

Here's what I'm trying to run:

> import os
> os.environ["HF_HUB_OFFLINE"] = "1"

> from transformers import pipeline

> import torch
> import triton_kernels
> 
> model_path = '/path/to/my/local/gpt-oss-120b'
> 
> generator = pipeline(
> "text-generation",
> model=model_path,
> torch_dtype="auto",
> device_map="auto"
> )
> 
> messages = [
>     {"role": "user", "content": "Explain what MXFP4 quantization is."},
> ]
>  
> result = generator(
>     messages,
>     max_new_tokens=200,
>     temperature=1.0,
> )
>  
> print(result[0]["generated_text"])

Getting quite a long traceback - some excerpts here:
`ValueError: Could not load model /path/to/my/local/gpt-oss-120b with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class transformers.models.gpt_oss.modeling_gpt_oss.GptOssForCausalLM'>`
`huggingface_hub.errors.OfflineModeIIsEnabled: Cannot reach https://huggingface.co/api/models/kernels-community/triton_kernels/revision/main: offline mode is enabled. To disable it, please unset the 'HF_HUB_OFFLINE' environment variable.`
`huggingface_hub.errors.LocalEntryNotFoundError: Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ps and downloads online, set 'HF_HUB_OFFLINE=0' as environment variable.`
