### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'to_legacy_cache'

### ISSUE THREAD

**Issue by wuxb45** [huggingface/transformers#28045]
### System Info

transformers 4.36.1.

```
transformers/models/llama/modeling_llama.py", line 1093, in forward
    next_cache = next_decoder_cache.to_legacy_cache() if use_legacy_cache else next_decoder_cache
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'to_legacy_cache'
```

This error pops up when running inference with llama 2 model with the new tranformers 4.36.1. I didn't test 4.36.0. It was running correctly with 4.35.x.

This seems to be related to changes from #26681, and commit 633215b.
@ArthurZucker and @younesbelkada according to suggestions in "Who can help?"

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Sorry that I don't have an easy reprod now. Here is the relavant stack trace:

```
  File "###transformers/generation/utils.py", line 1764, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "###transformers/generation/utils.py", line 2861, in sample
    outputs = self(
              ^^^^^
  File "###torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "###transformers/models/llama/modeling_llama.py", line 1181, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "###torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "###transformers/models/llama/modeling_llama.py", line 1093, in forward
    next_cache = next_decoder_cache.to_legacy_cache() if use_legacy_cache else next_decoder_cache
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'to_legacy_cache'
```

### Expected behavior

Crash with the provided stack track.

**Comment by younesbelkada** [comment]
hi @wuxb45 
can you share a fully reproducible snippet?

**Comment by liziniu** [comment]
I have the same issue with transofrmers 4.36.1. I am using DeepSpeed framework to generate a response and face this the same error.

**Comment by ArthurZucker** [comment]
We cannot help you if you don't share a reproducible snippet. The way this part of the code works should not trigger this error because the past key values are casted to the `DynamicCache` if `use_legacy_cache`. Thus there is probably a versioning issue

**Comment by junewgl** [comment]
> I have the same issue with transofrmers 4.36.1. I am using DeepSpeed framework to generate a response and face this the same error.

Me too. I also struggled with this problem for a long time, using deepspeed-chat to train reinforcement learning code.@liziniu

**Comment by wuxb45** [comment]
> hi @wuxb45 can you share a fully reproducible snippet?

I don't have the capacity to generate a reprod at this time. The issue was from running a code base forked from deepspeed chat's step 3. I'm sorry that I cannot provide more information now.

**Comment by stevie1023** [comment]
> I solved this by removing tensor parallel. It seems that merging perdevicetensor converted Cache to Tuple.

HI, i also faced the same issue. May I ask how you actually removed the tensor parallel if you are also using the deepspeed chat code?

**Comment by taozhang9527** [comment]
I had the same errors with `4.36.0` and `4.36.2` versions for Llama inferencing on multiple GPUs with `tensor_paralle`l package.

**Comment by taozhang9527** [comment]
I tried version `4.36.0.dev0` . I don't have the issue. Other versions including `4.37.0.dev0` will give the AttributeError.

**Comment by younesbelkada** [comment]
Hi everyone, please let us know whenever you can share a small reproducible snippet as we can't do anything without a repro to fix the bug

**Comment by taozhang9527** [comment]
@younesbelkada 

You can probably try the following code with different transformers version:

```
import torch
from tensor_parallel import TensorParallelPreTrainedModel
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

model_path = "meta-llama/Llama-2-7b-chat-hf"
model = LlamaForCausalLM.from_pretrained(model_path, torch_dtype=torch.float16)
model = TensorParallelPreTrainedModel(model, ["cuda:0", "cuda:1", "cuda:2", "cuda:3"])
tokenizer = LlamaTokenizer.from_pretrained(model_path)
inputs = tokenizer("Hi, how are you doing?", return_tensors="pt", add_special_tokens=False)
outputs = tokenizer.decode(model.generate(inputs["input_ids"].cuda(0), attention_mask=inputs["attention_mask"].cuda(0), max_length=256)[0], add_special_tokens=False)

print(outputs)
```
To me, only `4.36.0.dev0` works. After updating to new version, it won't work and I was not able to go back to the old  `4.36.0.dev0` version.

**Comment by ArthurZucker** [comment]
Alright this is pretty much a duplicate of #28003. We made a mistake by not advertising to test a bit more for other repos to get ready, feel free to share it on the `tensor_parallel` repo

**Comment by guojiapub** [comment]
To me, it works with `transformers==4.34.1`

**Comment by yiakwy-xpu-ml-framework-team** [comment]
Apparently this issue was introduced due to this this commit PR #26681 .

next_decoder_cache should be a cache, which means it is not well initialized as a cache.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
您好，邮箱主人会认真阅读！谢谢关注/

**Comment by yadavpa1** [comment]
I am facing a similar issue AttributeError: 'tuple' object has no attribute 'to_legacy_cache' while training Llama 7B. What is the concluded solution?

**Comment by ArthurZucker** [comment]
If you did not change your version of `transformers` that is expected. Upgrading to the latest / providing a repo should help!

**Comment by wangguojim** [comment]
transformers==4.35.2 works

**Comment by AsteriaCao** [comment]
> I tried version `4.36.0.dev0` . I don't have the issue. Other versions including `4.37.0.dev0` will give the AttributeError.

My transformers version is 4.45.0.dev0. It works

**Comment by wangguojim** [comment]
已收到

**Comment by code30x58** [comment]
https://youtu.be/tKCQcM5vfac?feature=shared

**Comment by wangguojim** [comment]
已收到
