### ISSUE TITLE
MT5Model(MT5Config()) fails with AttributeError: 'MT5Config' object has no attribute 'is_gated_act'

### ISSUE THREAD

**Issue by pbelevich** [huggingface/transformers#17578]
### System Info

```shell
current main branch, 4.20.0.dev0
```

### Who can help?

@patrickvonplaten @sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import *

model = MT5ForConditionalGeneration(MT5Config())
```

### Expected behavior

no error

**Comment by pbelevich** [comment]
I think it was introduced in https://github.com/huggingface/transformers/pull/17420

**Comment by sgugger** [comment]
cc @patil-suraj as well.
It would also be interesting to understand how it was not caught by any of the tests.
