### PR TITLE
Fix missing FP8 TP layer overrides

### LINKED ISSUE #48346: [Regression] FineGrainedFP8HfQuantizer crashes when expert TP overrides are absent
### System Info

- `transformers`: 5.16.0 and current `main`
- Python: 3.12.13
- PyTorch: 2.13.0+cu130
- Platform: Linux

### Who can help?

@SunMarc @MekkCyber

### Reproduction

`FineGrainedFP8HfQuantizer.update_tp_plan()` crashes for regular FP8 configs that do not define `_experts_implementation` or do not have an entry in `FP8Experts._impl_tp_layer_overrides`.

```python
from types import SimpleNamespace

from transformers import FineGrainedFP8Config
from transformers.quantizers.quantizer_finegrained_fp8 import FineGrainedFP8HfQuantizer

config = SimpleNamespace(
    base_model_tp_plan={"layers.*.mlp.experts": "grouped_gemm"}
)
quantizer = FineGrainedFP8HfQuantizer(FineGrainedFP8Config())
quantizer.update_tp_plan(config)
```

This raises:

```text
AttributeError: 'NoneType' object has no attribute 'get'
```

The lookup returns `None`, but the result is used unconditionally as a mapping. This also breaks loading normal Qwen FP8 models.

A fix and regression test are available in #48343.

### Expected behavior

Missing implementation-specific overrides should be treated as an empty mapping. The existing TP/EP plan should remain unchanged, while grouped-GEMM scale entries continue to be added.

### PR DESCRIPTION
**Pull request by changwangss**
[CPU CI](https://transformers-ci.lor-e.huggingface.cool/d/pytest-observability-by-pr/pytest-observability-branch?var-pr=48343) [GPU run-slow](https://transformers-ci.lor-e.huggingface.cool/d/pytest-observability-by-pr/pytest-observability-branch?var-pr=48343)

## What does this PR do?

Treats an unmapped FP8 experts implementation as having no TP layer overrides. This prevents `update_tp_plan()` from calling `.get()` on `None` for regular FP8 model configs while preserving grouped-GEMM scale plan handling.

Adds a focused regression test for configs without `_experts_implementation`.

Fixes #48346.

## Tests

- `python -m pytest -q tests/quantization/finegrained_fp8/test_fp8.py::FineGrainedFP8TPPlanTest`
- `ruff check src/transformers/quantizers/quantizer_finegrained_fp8.py tests/quantization/finegrained_fp8/test_fp8.py`

### CODE REVIEW

**Comment by changwangss** [comment]
The remaining CI failures appear unrelated to this FP8 change:

- `tests_torch [shard 7/8]`: `Tipsv2DptForDensePredictionTest::test_correct_missing_keys` failed on an unexpected size mismatch.
- `tests_fsdp_ci [shard 5/8]`: four `Qwen4ExpTextModelTest` FSDP save/load and checkpoint tests failed.

All other checks passed, including the shard containing the new regression test. I attempted to rerun the failed jobs, but external contributors do not have permission. Could a maintainer please rerun them?

File: tests/quantization/finegrained_fp8/test_fp8.py [hunk 1]
```diff
@@ -52,6 +53,17 @@ def _patch_no_accelerator():
...
+    def test_update_tp_plan_without_experts_implementation(self):
+        config = SimpleNamespace(base_model_tp_plan={"layers.*.mlp.experts": "grouped_gemm"})
+        quantizer = FineGrainedFP8HfQuantizer(FineGrainedFP8Config())
+
+        updated_config = quantizer.update_tp_plan(config)
+
+        self.assertEqual(updated_config.base_model_tp_plan["layers.*.mlp.experts"], "grouped_gemm")
+        self.assertEqual(updated_config.base_model_tp_plan["layers.*.mlp.experts_scale_inv"], "grouped_gemm")
+
+
```
Comment (SunMarc) [inline tests/quantization/finegrained_fp8/test_fp8.py]:
```suggestion
```

**Review by SunMarc — APPROVED** [review]
Thanks ! We can remove this test, this issue was breaking fp8 in general.

File: tests/quantization/finegrained_fp8/test_fp8.py [hunk 2]
```diff
@@ -16,6 +16,7 @@
 import tempfile
 import unittest
 from contextlib import ExitStack, contextmanager
+from types import SimpleNamespace
```
Comment (SunMarc) [inline tests/quantization/finegrained_fp8/test_fp8.py]:
```suggestion
```
