### ISSUE TITLE
[Regression] FineGrainedFP8HfQuantizer crashes when expert TP overrides are absent

### ISSUE THREAD

**Issue by changwangss** [huggingface/transformers#48346]
### System Info

- `transformers`: 5.16.0 and current `main`
- Python: 3.12.13
- PyTorch: 2.13.0+cu130
- Platform: Linux

### Who can help?

@SunMarc @MekkCyber

### Reproduction

`FineGrainedFP8HfQuantizer.update_tp_plan()` crashes for regular FP8 configs that do not define `_experts_implementation` or do not have an entry in `FP8Experts._impl_tp_layer_overrides`.

```python
from types import SimpleNamespace

from transformers import FineGrainedFP8Config
from transformers.quantizers.quantizer_finegrained_fp8 import FineGrainedFP8HfQuantizer

config = SimpleNamespace(
    base_model_tp_plan={"layers.*.mlp.experts": "grouped_gemm"}
)
quantizer = FineGrainedFP8HfQuantizer(FineGrainedFP8Config())
quantizer.update_tp_plan(config)
```

This raises:

```text
AttributeError: 'NoneType' object has no attribute 'get'
```

The lookup returns `None`, but the result is used unconditionally as a mapping. This also breaks loading normal Qwen FP8 models.

A fix and regression test are available in #48343.

### Expected behavior

Missing implementation-specific overrides should be treated as an empty mapping. The existing TP/EP plan should remain unchanged, while grouped-GEMM scale entries continue to be added.

**Comment by changwangss** [comment]
This regression was introduced by #47579 (`861f4c41ee46974debe5dde47dd0339146f4e6d2`). During the TP/DTensor refactor, the previous `if layer_overrides:` guard was removed, while `layer_overrides.get(...)` remained unconditional. As a result, configs without a matching `_experts_implementation` override now fail with `AttributeError`. @3outeille

**Comment by SunMarc** [comment]
Thanks for the report ! We will merge this PR and patch this asap as this break fp8 models in general
