### PR TITLE
safeguard torch distributed check

### LINKED ISSUE #26039: Regression: Need to guard torch.distributed.is_initialized with torch.distributed.is_available
### System Info

- `transformers` version: 4.33.1
- Platform: macOS-13.5-arm64-arm-64bit
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

Accessing via sentence-transformers so text models? @ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

My environment.yaml:

name: prompt_gym

channels:
  - conda-forge
  - pytorch

dependencies:
  - faiss
  - python=3.10
  - sentence-transformers

1. `mamba create` from the same directory as the environment.yaml
2. `mamba activate prompt_gym`
3.  From a python interpreter:
```python
import sentence_transformers
encoder = sentence_transformers.SentenceTransformer('intfloat/e5-small-v2', device='mps')
```
4. Receive error:
```text
  File "~/Documents/dev/gpt-experiments/common/src/msw_gpt_common/embedding.py", line 47, in encoder
    encoder = sentence_transformers.SentenceTransformer("intfloat/e5-base-v2", device="mps")
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2347, in from_pretrained
    if is_fsdp_enabled():
  File "~/mambaforge/envs/prompt_gym/lib/python3.10/site-packages/transformers/modeling_utils.py", line 118, in is_fsdp_enabled
    return torch.distributed.is_initialized() and strtobool(os.environ.get("ACCELERATE_USE_FSDP", "False")) == 1
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```

### Expected behavior

Transformers should not throw an error when loading an Automodel from a pretrained model. It should check that distributed processing is available before checking if it is initialized. See #17590 for an earlier version of the same bug. Regression was likely introduced by #25686.

### PR DESCRIPTION
**Pull request by pacman100**
# What does this PR do?
1. Resolves https://github.com/huggingface/transformers/issues/26039

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Review by muellerzr — APPROVED** [review]
LG2M, thanks!
