### PR TITLE
byebye torch 2.0

### LINKED ISSUE #37238: transformers 4.50 does not work with pytorch 2.0
### System Info

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

results in 

```
RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
module 'torch' has no attribute 'compiler'
```

I cannot run `transformers-cli env` for the same reason.

transformers 4.49 does not have this issue.

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

### Expected behavior

it should not give an error.

transformers 4.49 does not have this issue.

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

For #37137

Fixes #37238

### CODE REVIEW

**Comment by ydshieh** [comment]
not urgent, but @Rocketknight1 this PR is ready. The failing tests are irrelevant.

**Review by cyyever — APPROVED** [review]
PT 2.1 was released in 2023. In 2025 it's safe to require it as lower limit.

File: src/transformers/dependency_versions_table.py [hunk 1]
```diff
@@ -91,7 +91,7 @@
     "tiktoken": "tiktoken",
     "timm": "timm<=1.0.11",
     "tokenizers": "tokenizers>=0.21,<0.22",
-    "torch": "torch>=2.0",
+    "torch": "torch>=2.1",
```
Comment (cyyever) [inline src/transformers/dependency_versions_table.py:94]: Can we specify `torch>=2.1.1`

File: src/transformers/quantizers/quantizer_fbgemm_fp8.py [hunk 2]
```diff
@@ -48,7 +45,7 @@ def __init__(self, quantization_config, **kwargs):
         self.quantization_config = quantization_config
 
     def validate_environment(self, *args, **kwargs):
-        if not is_torch_available() or version.parse(importlib.metadata.version("torch")) < version.parse("2.1.0"):
+        if not is_torch_available():
             raise ImportError(
                 "Using fbgemm fp8 quantization requires torch > 2.1.0"
```
Comment (cyyever) [inline src/transformers/quantizers/quantizer_fbgemm_fp8.py:50]: requires torch >= 2.1.0

**Review by SunMarc — APPROVED** [review]
Thanks for updating ! Just a few nits

File: src/transformers/dependency_versions_table.py (hunk 1 above)
Comment (ydshieh) [reply src/transformers/dependency_versions_table.py:94]: I see. Given that most people are likely using newer torch versions, such specific pin (to the patch version) isn't really necessary IMO.

IIRC, when we need to pin such patch version(s), the reasons were earlier patch version(s) have serious issues and make several models not useable. One example I remembered was audio models failed at some point.

**Review by Rocketknight1 — APPROVED** [review]
Yes, this LGTM! As long as we keep the function for backward compatibility with remote code I think this is pretty safe, and cleans things up a lot!

**Comment by ydshieh** [comment]
Going to merge, the failing tests

> tests/models/llama4/test_processor_llama4.py

are irrelevant to this PR and known already failing on main.

File: src/transformers/dependency_versions_table.py (hunk 1 above)
Comment (ydshieh) [reply src/transformers/dependency_versions_table.py:95]: I will merge as it is. If we find such pin is necesssary, we can update in the future.
