### ISSUE TITLE
Many import errors after update from 4.57.0 to 5.5.0

### ISSUE THREAD

**Issue by marchcat69** [huggingface/transformers#45278]
### System Info

After updating Transformers from version 4.57.0 to version 5.5.0, I get the following import errors: 
ImportError: cannot import name 'HybridCache' from 'transformers'
ImportError: cannot import name 'AutoModelForVision2Seq' from 'transformers'
ImportError: cannot import name 'PretrainedConfig' from 'transformers.modeling_utils'

What should I do to avoid them?

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers.modeling_utils import PretrainedConfig, PreTrainedModel
from transformers import Cache, DynamicCache, EncoderDecoderCache, HybridCache, PreTrainedModel

### Expected behavior

No import errors

**Comment by ibrahim1023** [comment]
I reproduced this in clean installs.

On `transformers==5.5.0` with `torch`, these fail:
- `from transformers import HybridCache`
- `from transformers import AutoModelForVision2Seq`
- `from transformers.modeling_utils import PretrainedConfig`

On `transformers==4.57.0`, the same imports succeed, so this does look like a real compatibility break.

This seems mixed rather than one bug:
- `AutoModelForVision2Seq` looks tied to the `vision2seq` -> `image-text-to-text` rename (`AutoModelForImageTextToText` works in `5.5.0`).
- `PretrainedConfig` still imports from `transformers` and `transformers.configuration_utils`, but not from `transformers.modeling_utils`.
- `HybridCache` does not import from `transformers` in `5.5.0`.

I also found likely overlap with `#40695` and `#37623`.

Would maintainers want a focused compatibility fix for the `PretrainedConfig` import path only, or is this issue expected fallout from the rename/removal work already in progress?

**Comment by Rocketknight1** [comment]
The upgrade to version `5` did cause compatibility breaks at some points. This was part of a deliberate cleanup. We try to avoid these breaks most of the time, but on occasion the cruft builds up enough to force a major version with breaking changes.

**Comment by Uchihayht** [comment]
degrade peft version
