### ISSUE TITLE
I can not import transformers

### ISSUE THREAD

**Issue by over-shine** [huggingface/transformers#3179]
# 🐛 Bug

## Information
when I execute "from transformers import TFBertModel, BertModel" in ipython, the error, "ImportError: cannot import name 'BartConfig' from 'transformers.configuration_auto'" was raised.
This error occured after the tensorflow update from version 2.0 to version 2.1 and the python update from version 3.6 to 3.7.

In addition, after I update the python from version 3.6 to 3.7, I installed torch1.4 and tensorflow2.1 in a same env, the "import" is always failed but when I "import transformers" in other env which only include torch1.4 and python3.7, it succeed
I want to know how to make it. Thank you.

- `transformers` version:2.5.1
- Platform: windows10
- Python version: 3.7.6
- PyTorch version (GPU?):GPU1.4
- Tensorflow version (GPU?):GPU2.1

**Comment by over-shine** [comment]
I have solved it by rebooting my computer and reinstall some modules that transformers can not found but have been installed

**Comment by AGregorc** [comment]
This issue still exists. I have Tensorflow 2.1 with GPU and transformers version 2.8.0

I tried with rebooting and creating new conda environments multiple times but still no success :(

**Comment by over-shine** [comment]
I can import it and my python version is 3.7.6 , 2.8.0 for transformers and 2.1 for tf. Maybe you could try to upgrade your python if its' version is under 3.7.

**Comment by over-shine** [comment]
> This issue still exists. I have Tensorflow 2.1 with GPU and transformers version 2.8.0
> 
> I tried with rebooting and creating new conda environments multiple times but still no success :(

I can import it and my python version is 3.7.6 , 2.8.0 for transformers and 2.1 for tf. Maybe you could try to upgrade your python if its' version is under 3.7.

**Comment by AGregorc** [comment]
Hmm, the next day I tried it again with the same environment and it works xD Probably because of rebooting or something. But I also rebooted the first day, idk...
