### ISSUE TITLE
ImportError: cannot import name 'Qwen2_5_VLImageProcessor' from 'transformers.models.qwen2_5_vl' (/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/__init__.py)

### ISSUE THREAD

**Issue by LaoWangGB** [huggingface/transformers#36246]
### System Info

vllm==0.7.2
transformers==4.49.0

### Who can help?

ImportError: cannot import name 'Qwen2_5_VLImageProcessor' from 'transformers.models.qwen2_5_vl' (/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/__init__.py)

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

from vllm import LLM
model = LLM(model="Qwen2.5-VL-7B, trust_remote_code=True, dtype="bfloat16")

### Expected behavior

I confirm the version:4.49.0_dev contains a script named image_processing_qwen2_5_vl.py, but version 4.49.0 remove it.
ImportError: cannot import name 'Qwen2_5_VLImageProcessor' from 'transformers.models.qwen2_5_vl' (/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/__init__.py)

**Comment by 2710932616** [comment]
i add Qwen2VLImageProcessor， it‘s work.

![Image](https://github.com/user-attachments/assets/6b575d7d-53b1-48e2-ba72-202033084fac)

![Image](https://github.com/user-attachments/assets/975a363f-78ce-4e17-b0e5-ea47f30fa1e7)

**Comment by 2710932616** [comment]
> i add Qwen2VLImageProcessor， it‘s work.
> 
> ![Image](https://github.com/user-attachments/assets/6b575d7d-53b1-48e2-ba72-202033084fac)
> 
> ![Image](https://github.com/user-attachments/assets/975a363f-78ce-4e17-b0e5-ea47f30fa1e7)

I found that the vllm has fixed this problem in [https://github.com/vllm-project/vllm/pull/13286](https://github.com/vllm-project/vllm/pull/13286), But the release version has not been released yet, so installing the latest vllm should also solve this problem.

**Comment by o0t1ng0o** [comment]
it works when upgrade transformer version to 4.50
