### ISSUE TITLE
transformers==4.55.2 still imports TFPreTrainedModel even with TRANSFORMERS_NO_TF=1"

### ISSUE THREAD

**Issue by Yanshuptl18** [huggingface/transformers#40292]
### System Info

**Describe the bug**
When using transformers==4.55.2 with TensorFlow disabled (TRANSFORMERS_NO_TF=1), the library still attempts to import TFPreTrainedModel internally, causing an ImportError even though only PyTorch is being used.

**Environment info**
-> Python version: 3.13 (Windows 11, x86_64-pc-windows-msvc)
-> Transformers version: 4.55.2
-> Accelerate version: 1.10.0
-> Torch version: 2.5.0+cpu
-> TensorFlow: not installed (intentionally, since PyTorch is used)

**Error message**
ImportError: cannot import name 'TFPreTrainedModel' from 'transformers.modeling_tf_utils'

**Additional context**
This bug prevents PyTorch-only workflows from working with Transformers 4.55.2.
TensorFlow ≥2.16.1 is also not installable on Python 3.13, which makes this issue more severe.

**Related issue :**  This may be caused by a regression in recent refactoring of modeling_tf_utils imports.

**Suggested fix : ** Respect TRANSFORMERS_NO_TF=1 when importing, and avoid hard imports of TensorFlow modules if TF is disabled.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install transformers==4.55.2 with PyTorch only (no TensorFlow).
2. Set environment variable:
               export TRANSFORMERS_NO_TF=1
(or set TRANSFORMERS_NO_TF=1 on Windows)
3. Run a script that only uses PyTorch models (e.g., Trainer with BertForSequenceClassification).

### Expected behavior

The library should not attempt to import TensorFlow components (TFPreTrainedModel) when TRANSFORMERS_NO_TF=1 is set, and no TensorFlow should be required.

**Comment by Rocketknight1** [comment]
This is very surprising to me! Can you paste the script you used? In general we're deprecating TF/JAX support, so we definitely don't want TF interfering with Torch workflows

**Comment by AntilMB** [comment]
have the same issue after installing tf2

ubuntu 24
python 3.13
sentence-transformers==5.1.0
transformers==4.55.4


from sentence_transformers import SentenceTransformer


File [~/anaconda3/lib/python3.13/site-packages/transformers/integrations/integration_utils.py:44]
     41 if os.getenv("WANDB_MODE") == "offline":
     42     print("⚙️  Running in WANDB offline mode")
---> 44 from .. import PreTrainedModel, TFPreTrainedModel, TrainingArguments

**Comment by id01** [comment]
Ran into the same issue. Band-aid fix for now is to edit `integration_utils.py` and remove TFPreTrainedModel and the elif block that compares to it.

**Comment by Rocketknight1** [comment]
hey @id01, would you be willing to make a PR? Since we're deprecating TF, it's fine to lose some features to ensure that Torch keeps working properly (for example, we could just do something dirty to avoid the import like checking for a "TFPreTrainedModel" string in the class hierarchy or something, or just guard the import behind `is_tf_available`)

**Comment by steveepreston** [comment]
Is there any os env named `TRANSFORMERS_NO_TF`?
i can not find it in transformers source code!

**Comment by Rocketknight1** [comment]
Hi @steveepreston, TF support has now been fully removed, so those env vars should be gone too. This issue shouldn't be relevant anymore!

**Comment by steveepreston** [comment]
@Rocketknight1 Great! Thanks for the note!
