### ISSUE TITLE
AttributeError: 'Gemma3Config' object has no attribute 'vocab_size'

### ISSUE THREAD

**Issue by jumelet** [huggingface/transformers#36683]
### System Info

v4.50.0.dev0

### Who can help?

@ArthurZucker 
@LysandreJik 
@xenova 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am trying to run the new Gemma3 model, using version '4.50.0.dev0'.

When loading the model I get the error: 'Gemma3Config' object has no attribute 'vocab_size'.

Looking into this it seems Gemma3Config has `vocab_size` nested in a "text_config" attribute. 

I try to load the model as AutoModelForCausalLM, running it with Gemma3ForConditionalGeneration does not raise this issue. Am I wrong in assuming I can run Gemma 3 as AutoModelForCausalLM?

### Expected behavior

Loading the model as AutoModelForCausalLM.from_pretrained without issue.

**Comment by ZipingL** [comment]
I encountered the same issue as well. One might assume that adding `vocab_size` to the model's `config.json` would resolve the problem, especially since there is a `vocab_size` present in [this `config.json`](https://huggingface.co/google/gemma-3-1b-it/blob/main/config.json).

However, even after making that adjustment, I faced a multitude of other errors related to missing configuration keys in the transformers loader.

### **The Persistent Challenge: Beyond Vocabulary Size**

The initial error I encountered was a `KeyError` indicating a missing `vocab_size` in the configuration. This issue is merely the *surface* of a more profound systemic problem when loading large transformer models like Gemma in environments such as Text-Generation-WebUI. While adding the missing `vocab_size` resolves the immediate `KeyError`, it does not provide a comprehensive solution; instead, it triggers a cascade of subsequent errors related to *other* missing configuration options. This is not simply a matter of a few isolated omissions; it reflects a fundamental mismatch between the model’s expectations and the configuration capabilities of the environment.

### **The Cascade of Missing Configuration Options**

After addressing the `vocab_size` issue, I began encountering a series of `AttributeError` and `KeyError` exceptions, each necessitating the addition of yet another configuration option. Some of the critical parameters include:

*   **`hidden_size`**: The model requires a specific hidden size, which must be explicitly included in the configuration.
*   **`num_hidden_layers`**: The expected number of hidden layers needs to be defined.
*   **`rope_theta` & `rope_base`**: These parameters are essential for the RoPE implementation and must be present for accurate position embedding calculations.
*   **`intermediate_size`**: This defines the size of the intermediate feed-forward layer within the transformer.
*   **`num_key_value_heads`**: This is crucial for grouped-query attention mechanisms.
*   **`hidden_activation`**: This specifies the activation function used in the hidden layers.
*   **`num_attention_heads`**: This indicates the number of attention heads.

The process quickly becomes a tedious cycle: add one option, trigger another error, add that option, and so forth. Even after meticulously including *all* seemingly necessary configuration parameters, the `Gemma3` model may still fail to load correctly. This is often due to an internal process known as "dynamic model initialization," compounded by the use of "meta tensors."

**Comment by sam-paech** [comment]
I resolved this error by using Gemma3ForConditionalGeneration per the model card:

```
from transformers import AutoProcessor, Gemma3ForConditionalGeneration
model = Gemma3ForConditionalGeneration.from_pretrained(
    model_id, device_map="auto"
)
```

I'm getting a warning about "The model 'Gemma3ForConditionalGeneration' is not supported for text-generation", but inference works.

**Comment by jumelet** [comment]
@ZipingL , I think the issue is mainly that by using the AutoModel initialization it somehow passes an `Gemma3Config` to the Gemma3TextModel, instead of a `Gemma3TextConfig`, here at L619:

https://github.com/huggingface/transformers/blob/v4.49.0-Gemma-3/src/transformers/models/gemma3/modeling_gemma3.py#L619

All the config args you mention would be in Gemma3Config["text_config"]. Maybe it happens because AutoModel uses AutoConfig to initialize the config, which probably defaults to `Gemma3Config`, instead of `Gemma3TextConfig`?

**Comment by somerandomguyontheweb** [comment]
In [`models/auto/modeling_auto.py`, line 523](https://github.com/huggingface/transformers/blob/50d3530a/src/transformers/models/auto/modeling_auto.py#L523) I've tried replacing `Gemma3ForCausalLM` with `Gemma3ForConditionalGeneration` and it works for me – Gemma 3 4B successfully loads with `AutoModelForCausalLM.from_pretrained`. I'm only interested in text generation though, so not sure if image processing would be affected by this quick fix.

**Comment by Rocketknight1** [comment]
Hugging Face maintainer here: I can reproduce the `'Gemma3Config' object has no attribute 'vocab_size'` error. Raising the issue internally and we'll try to get a fix ASAP!

**Comment by rdodev** [comment]
Is there a way to use the `Gemma3ForConditionalGeneration` with vLLM?

**Comment by zucchini-nlp** [comment]
Hey all! Yes, Gemma3ForCausalLM cannot be loaded with auto mapping unfortunately, and it is a known limitation. We have it noted, and the reason is that the same hub model-id is loaded with two different tasks in transformers. That in turn causes issues when we try to infer the config type for CausalLM

There could be a dirty workaround, but the idea was to not support AutoModel until a solid solution is available

**Comment by yonggui521** [comment]
I have the same error when I use vllm images :v0.7.3 with transformers v4.50.0.dev0

**Comment by bjj** [comment]
> I have the same error when I use vllm images :v0.7.3 with transformers v4.50.0.dev0

You need to build vLLM from source. Solution is mentioned in this thread: https://github.com/vllm-project/vllm/issues/14734

When you get it right your version will look like this:
```
$ pip list | grep vllm
vllm                              0.7.4.dev418+gd47807ba.precompiled /home/xxx/vllm/vllm
```

**Comment by ropz12138** [comment]
> > 当我使用 vllm images :v0.7.3 与 transformers v4.50.0.dev0 时也出现同样的错误
> 
> 您需要从源代码构建 vLLM。此线程中提到了解决方案：[vllm-project/vllm#14734](https://github.com/vllm-project/vllm/issues/14734)
> 
> 当你正确完成时，你的版本将如下所示：
> 
> ```
> $ pip list | grep vllm
> vllm                              0.7.4.dev418+gd47807ba.precompiled /home/xxx/vllm/vllm
> ```

why your vllm is 0.7.4, i can only find 0.7.3. Is my image site "gitclone.com" is wrong?

**Comment by rohitgr7** [comment]
hey @Rocketknight1 !!

any idea on when it is going to be fixed and transformers's new version is going to be released with stable gemma3 support?

**Comment by ropz12138** [comment]
running gemma3 with transformers(the official tutorial on Hugging Face), but when running it with vllm, I encounter the error: AttributeError: 'Gemma3Config' object has no attribute 'vocab_size'.

**Comment by ArthurZucker** [comment]
I don't think the issue in on `transformers`'s side, we'll get the backend fixed

**Comment by gante** [comment]
Hi folks 👋 

With #36741, which will be included in the next patch release, you can load the text-only part of gemma3 with `AutoModelForCausalLM`:

```py
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("google/gemma-3-4b-it", device_map="auto")
```

Until then, you can do `pip install --upgrade git+https://github.com/huggingface/transformers.git` to install from `main` and unlock this fix.

______________________

We apologize for the slower reply: we were discussing a systemic solution for this problem, as we expect it to happen with more modalities in the near future :) #36741 is a band-aid, a more scalable solution is in our plans.

**Comment by jumelet** [comment]
This seems like a different issue than the one I opened this issue for (and which is now resolved); if your issue is still present in the patched release that gante mentioned above it is probably better to open a new issue for this.

**Comment by zeb209** [comment]
I am seeing this issue as well. Any updates?

**Comment by ZipingL** [comment]
> [@ZipingL](https://github.com/ZipingL) , I think the issue is mainly that by using the AutoModel initialization it somehow passes an `Gemma3Config` to the Gemma3TextModel, instead of a `Gemma3TextConfig`, here at L619:
> 
> https://github.com/huggingface/transformers/blob/v4.49.0-Gemma-3/src/transformers/models/gemma3/modeling_gemma3.py#L619
> 
> All the config args you mention would be in Gemma3Config["text_config"]. Maybe it happens because AutoModel uses AutoConfig to initialize the config, which probably defaults to `Gemma3Config`, instead of `Gemma3TextConfig`?
> 
> Edit: Looks like my hunch was right, the `Gemma3ForConditionalGeneration` even uses `AutoModelForCausalLM` to initialize the language_model but passes `config.text_config` to it: https://github.com/huggingface/transformers/blob/v4.49.0-Gemma-3/src/transformers/models/gemma3/modeling_gemma3.py#L1120

@jumelet, Thanks, that fixed it for me.

- I managed to get it running smoothly with a custom Python script. However, its integration with tools like Ollama, text-generation-webui, and LM Studio still presents challenges, similar to what I experienced with Gemma 2.
- Due to my hardware limitations (an older Turing GPU), I depend on quantized versions of Gemma 3, making these ongoing compatibility issues particularly frustrating.
- While the initial fix resolved the immediate error, it did not tackle the broader challenges of seamless integration with common LLM interfaces. The absence of the vocab.txt file in the 1B model version further underscores these inconsistencies. Consequently, I have started exploring more compatible models to overcome these obstacles.

**Comment by delip** [comment]
@ZipingL and @jumelet, what was the fix? I am using unsloth and I see this error too. cc: @danielhanchen

**Comment by ai-nikolai** [comment]
@Rocketknight1  - encountering this issue with SalesForce / Codegen model as well..

How can one fix this for these models?

**Comment by mostafatouny** [comment]
I have the identical problem but with Qwen3.5. The mentioned solution here to pass `TextConfig` in place of `Config` fixes it.

```py
from transformers import Qwen3_5ForCausalLM, Qwen3_5Tokenizer, Qwen3_5TextConfig

modelId = "Qwen/Qwen3.5-0.8B"

# solution here. by default, Qwen3_5Config is fetched which is inconsistent with `Qwen3_5ForCausalLM`
config = Qwen3_5TextConfig.from_pretrained(modelId)

model = Qwen3_5ForCausalLM.from_pretrained(modelId, config = config, device_map = "auto", torch_dtype = "auto")
```

**Comment by Rocketknight1** [comment]
This is interesting, cc @zucchini-nlp - do we have an issue where a class is usually a VLM but smaller checkpoints are CLMs only, and they get the wrong `AutoConfig` as a result?

**Comment by zucchini-nlp** [comment]
Weird, it should work given that the config class is defined correctly. I remember fixing it when gemma3 was released

https://github.com/huggingface/transformers/blob/4ec84a022d2ba1efb2cbbdc9eb415e4190113d22/src/transformers/models/qwen3_5/modeling_qwen3_5.py#L1776


Will take a closer look tomorow

**Comment by Mevrael** [comment]
Yeah, the same problem with qwen3.5

AttributeError: 'Qwen3_5Config' object has no attribute 'vocab_size'

```python
---> 55     self.model = AutoModelForCausalLM.from_pretrained(
     56         self.model_id,
     57         quantization_config=self.quant_config,
     58         device_map="auto",
     59     )
```

**Comment by zucchini-nlp** [comment]
Works on `main` branch and also in v5.2.0. Are you by chance using a very old release version @mostafatouny ?

```python
model = Qwen3_5ForCausalLM.from_pretrained("Qwen/Qwen3.5-0.8B", device_map="cuda", dtype="bfloat16")
model = AutoModelForCausalLM.from_pretrained(modelId, device_map="cuda", dtype="bfloat16") # also works
```

**Comment by Mevrael** [comment]
No, it doesn't work

```python
from transformers import AutoModelForCausalLM

model_id = "Qwen/Qwen3.5-4B"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto"
)
```

AttributeError: 'Qwen3_5Config' object has no attribute 'vocab_size'

Python: 3.14.3
transformers: 5.3.0

**Comment by zucchini-nlp** [comment]
I believe it might be related to the local env. I even tried to reproduce in colab, and it loads without errors 👀  Super weird that many ppl are reporting it

https://colab.research.google.com/drive/1HKBj-XLxI_W22MY9jjK_rFqgDBxsjqCv?usp=sharing

**Comment by mostafatouny** [comment]
@zucchini-nlp, I am using `huggingface_hub v1.7.1` and `transformers v5.3.0`. Here is my [requirements.txt](https://github.com/user-attachments/files/26125845/requirements.txt) file, through which I reproduce my Python v3.14 virtual environment.

Note I had a functioning code, and once I updated my Arch OS, the bug did emerge without any code modification. Is `transformers` dependent on OS kernel drivers in any way?

**Comment by Mevrael** [comment]
colab link above uses python 3.12

I tested 3.12 and it works.

Python 3.14 is the issue.

**Comment by zucchini-nlp** [comment]
I'll just re-open it due to a number of issues from different users, I think this is a valid bug. 

> Python 3.14 is the issue.

Interesting, my local env also has old python so might be. If anyone has time and wants to dig further into reasons and possible fixes, that would much appreciated

The best place to start from would be here, which decided on config class

https://github.com/huggingface/transformers/blob/f5e573080ae0838799c1f9a0ba28be8431120b56/src/transformers/models/auto/auto_factory.py#L379-L380

**Comment by mostafatouny** [comment]
@zucchini-nlp, 

I debugged and found

```
print(model_class)
<class 'transformers.models.qwen3_5.modeling_qwen3_5.Qwen3_5ForCausalLM'>`

print(model_class.config_class)
<class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5Config'>
```

where the expected behavior is
```
print(model_class.config_class)
<class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5TextConfig'>
```

I guess the problem is in

https://github.com/huggingface/transformers/blob/cef283004847f44c2c07e48670ba524b7cb2ac24/src/transformers/modeling_utils.py#L1224

where it fails, returning `None`, in place of 

https://github.com/huggingface/transformers/blob/f5e573080ae0838799c1f9a0ba28be8431120b56/src/transformers/models/qwen3_5/modeling_qwen3_5.py#L1776

I guess the root cause is that in Python 3.14, [Lazy Annotations](https://realpython.com/python-annotations/) are introduced, where annotations are lazy by default ([PEP 649](https://peps.python.org/pep-0649/)).

---

A counter evidence of that hypothesis, is that if it were the true cause, then

https://github.com/huggingface/transformers/blob/f5e573080ae0838799c1f9a0ba28be8431120b56/src/transformers/models/gemma3/modeling_gemma3.py#L597

would have failed also. However, `gemma-3-*` works in my local setup with Python 3.14

```
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
model = AutoModelForCausalLM.from_pretrained("google/gemma-3-270m-it", device_map = "auto", torch_dtype = "auto")
```

---

Debugging `__init_subclass__` is problematic, since `PreTrainedModel` is a parent of many subclasses. I may allocate time after two weeks. Sorry for not being more helpful.

**Comment by zucchini-nlp** [comment]
Great investigation @mostafatouny, thanks a lot! I got my env updated to py3-14 so I can dig more on Sunday and read through Py3.14 release notes

**Comment by mostafatouny** [comment]
@zucchini-nlp, Thank you for the kind words. Here are more debugging logs

```
        # defined in this particular subclass
        child_annotation = cls.__dict__.get("__annotations__", {}).get("config", None)
        child_attribute = cls.__dict__.get("config_class", None)

        # defined in the class (this subclass or any parent class)
        full_annotation = get_type_hints(cls).get("config", None)
        full_attribute = cls.config_class

        print(f"Subclass: {cls.__name__}")
        print(f"  child_annotation : {child_annotation}")
        print(f"  child_attribute  : {child_attribute}")
        print(f"  full_annotation  : {full_annotation}")
        print(f"  full_attribute   : {full_attribute}")

        # priority (child class_config -> child annotation -> global class_config -> global annotation)
        if child_attribute is not None:
            print("child_attribute is fired")
            cls.config_class = child_attribute
        elif child_annotation is not None:
            print("child_annotation is fired")
            cls.config_class = child_annotation
        elif full_attribute is not None:
            print("full_attribute is fired")
            cls.config_class = full_attribute
        elif full_annotation is not None:
            print("full_annotation is fired")
            cls.config_class = full_annotation
        print(cls.config_class)
```

which prints

```
Subclass: Qwen3_5ForCausalLM
  child_annotation : None
  child_attribute  : None
  full_annotation  : <class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5TextConfig'>
  full_attribute   : <class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5Config'>
full_attribute is fired
<class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5Config'>
```

It will be fixed if `full_annotation` preceedes `full_attribute`. Are you sure of the order?

**Comment by zucchini-nlp** [comment]
As per comment, seems like the order is intended, so that we first check this specific subclass's attributes and if not found move to global vars. I also reproduced the issue and I see that in 3.14 the class dict has `__annotations_cache__` instead of `__annotations__` which is the reason i believe

Can you open a PR and add a test case?

**Comment by mostafatouny** [comment]
@zucchini-nlp, couple of remarks.

```
        print(f"Subclass: {cls.__name__}")
        # defined in this particular subclass
        print(f"  start             : {list(cls.__dict__.keys())}")
        child_annotation = cls.__dict__.get('__annotations_cache__', {}).get('config', None)
        print(f"  after child_annotation             : {list(cls.__dict__.keys())}")
        child_attribute = cls.__dict__.get("config_class", None)
        print(f"  after child_attribute             : {list(cls.__dict__.keys())}")

        # defined in the class (this subclass or any parent class)
        full_annotation = get_type_hints(cls).get("config", None)
        print(f"  after full_annotation             : {list(cls.__dict__.keys())}")
        full_attribute = cls.config_class
        print(f"  after full_attribute            : {list(cls.__dict__.keys())}")
```
prints
```
  start             : ['__module__', '__firstlineno__', '_tied_weights_keys', '_tp_plan', '_pp_plan', '_keys_to_ignore_on_load_unexpected', '__init__', 'forward', '__annotate_func__', '__static_attributes__', '__doc__']
  after child_annotation             : ['__module__', '__firstlineno__', '_tied_weights_keys', '_tp_plan', '_pp_plan', '_keys_to_ignore_on_load_unexpected', '__init__', 'forward', '__annotate_func__', '__static_attributes__', '__doc__']
  after child_attribute             : ['__module__', '__firstlineno__', '_tied_weights_keys', '_tp_plan', '_pp_plan', '_keys_to_ignore_on_load_unexpected', '__init__', 'forward', '__annotate_func__', '__static_attributes__', '__doc__']
  after full_annotation             : ['__module__', '__firstlineno__', '_tied_weights_keys', '_tp_plan', '_pp_plan', '_keys_to_ignore_on_load_unexpected', '__init__', 'forward', '__annotate_func__', '__static_attributes__', '__doc__', '__annotations_cache__']
  after full_attribute            : ['__module__', '__firstlineno__', '_tied_weights_keys', '_tp_plan', '_pp_plan', '_keys_to_ignore_on_load_unexpected', '__init__', 'forward', '__annotate_func__', '__static_attributes__', '__doc__', '__annotations_cache__']
```

`__annotations_cache__` is created lazily by `get_type_hints()` when it evaluates and caches the annotations. That seems to be the new behaviour of Python 3.14, where the cache doesn't exist until something triggers annotation evaluation.

The following works

```
        import annotationlib
        print(f"Subclass: {cls.__name__}")
        # defined in this particular subclass
        # child_annotation = cls.__dict__.get('__annotations_cache__', {}).get('config', None)
        child_annotation = annotationlib.get_annotations(cls, eval_str=True, format=annotationlib.Format.VALUE).get("config", None)
        child_attribute = cls.__dict__.get("config_class", None)

        # defined in the class (this subclass or any parent class)
        # full_annotation = get_type_hints(cls).get("config", None)
        full_annotation = annotationlib.get_annotations(cls, eval_str=True, format=annotationlib.Format.VALUE).get("config", None)
        full_attribute = cls.config_class

        print(f"  child_annotation : {child_annotation}")
        print(f"  child_attribute  : {child_attribute}")
        print(f"  full_annotation  : {full_annotation}")
        print(f"  full_attribute   : {full_attribute}")

        # priority (child class_config -> child annotation -> global class_config -> global annotation)
        if child_attribute is not None:
            print("child_attribute is fired")
            cls.config_class = child_attribute
        elif child_annotation is not None:
            print("child_annotation is fired")
            cls.config_class = child_annotation
        elif full_attribute is not None:
            print("full_attribute is fired")
            cls.config_class = full_attribute
        elif full_annotation is not None:
            print("full_annotation is fired")
            cls.config_class = full_annotation
        print(cls.config_class)
```
which prints
```
Subclass: Qwen3_5ForCausalLM
  child_annotation : <class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5TextConfig'>
  child_attribute  : None
  full_annotation  : <class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5TextConfig'>
  full_attribute   : <class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5Config'>
child_annotation is fired
<class 'transformers.models.qwen3_5.configuration_qwen3_5.Qwen3_5TextConfig'>
```
In [this tutorial](https://realpython.com/python-annotations/), it is explicitly mentioned

> Note: Starting from Python 3.14, you need to access the module’s .__annotations__ attribute at least once before the __annotations__ variable becomes visible in the global namespace.

> use annotationlib.get_annotations() and typing.get_type_hints() for more robust introspection.

After those fixes, the following works now:
```
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3.5-0.8B",device_map = "auto",torch_dtype = "auto",
)
```

I believe we found the cause root. Would you like to open a new PR using `annotationlib.get_annotations()`, @zucchini-nlp?

**Comment by zucchini-nlp** [comment]
@mostafatouny i went to git blame to see the history and found that `config_class` is here only for BC added recently. And since the doc for `get_type_hints` (https://docs.python.org/3.10/library/typing.html#typing.get_type_hints) states that the current class'es annotations take precedence over other classes in mro, I think your first suggestion on changing the order was correct and the order should've been different from the beginning

We just didn't see issues because `__annotations__` were always there in old python, which isn't true anymore with lazy creation

**Comment by Mevrael** [comment]
This code works btw, so AutoConfig can correctly get the right class, why it's not just being used? Or what was the intended algorithm for Auto classes, how it shall fetch the correct one automatically, and if it is looking for a text config all the time, then why not just to use get_text_config() internally as well?

Relying too much on magic, annotations and checking for attributes may not be the best approach. I believe there shall be some kinda mapping internally for model types and respective classes.

```python
config = AutoConfig.from_pretrained(model_id)

config = config.get_text_config()

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    config=config,
    device_map="cuda",
    dtype="bfloat16"
)
```

**Comment by zucchini-nlp** [comment]
@Mevrael Unfortunately we can't want to enforce `get_text_config()` for all models as it breaks models that rely on `AutoModelForCausalLM` and need the whole config to be init. We already tried that in the past and had to revert it back due to a number of issues. It was decided that checking with model classes' expected config is more reliable

The "magic" will all typing and stuff comes for different reasons, from https://github.com/huggingface/transformers/pull/39132. The PR removed `cls.config_class`  in favor of `cls.config`, so it can resolve the typing hint. The whole block that infers correct config class is thus legacy and is there only for BC. Ideally if we could just drop `config_class`, it would be much easier and we won't need the "magic"

**Comment by mostafatouny** [comment]
> I think your first suggestion on changing the order was correct and the order should've been different from the beginning

@zucchini-nlp, I'd always be happy to contribute.

**Comment by Mevrael** [comment]
I see that there is a huge const CONFIG_MAPPING_NAMES and it looks up the Config class first

and then a model class is determined from the config class.

Qwen3_5ForCausalLM

which sets `self.model = Qwen3_5TextModel(config)` in init

where the wrong config class is passed, when it expects Qwen3_5TextConfig

Shouldn't the CONFIG_MAPPING_NAMES by default point qwen3.5 to Qwen3_5TextConfig instead of Qwen3_5Config?

---

And wouldn't it be better to simply let the main class determine everything and just import the right folder/module dynamically? You don't plan on keeping adding new items to the mapping dictionaries across multiple files every time someone adds a new model and a folder, don't you? :-)

So a Base interface class for instance could have a static method getConfigClass() that returns the right class, and the model class implementing the Base would have to implement this method and return a class, not an object

For example

model = AutoResolver.loadModel('qwen/qwen3.5') would look for a qwen folder and qwen3_5_model file
it would then import it dynamically and hence the model would be of a Qwen3_5_Model class and model.getConfig() would return the right configuration, or the same getConfigClass() from a parent class.

auto class could also automatically fetch the config class

config_cls = AutoResolver.getConfigClass('qwen/qwen3.5')
config = config_cls(...)
or a shortcut
config = AutoConfig('qwen/qwen3.5', ...)
model = AutoModel('qwen/qwen3.5', config=config)

or throw an error if config and model name mismatch right there in the init.

**Comment by zucchini-nlp** [comment]
> Shouldn't the CONFIG_MAPPING_NAMES by default point qwen3.5 to Qwen3_5TextConfig instead of Qwen3_5Config?

Then we won't be able to load the `Qwen3_5ForConditionalGeneration` model, it needs `Qwen3_5Config`, so no. We are trying to use a model which is initially a VLM and load it as an LLM, cropping off the vision support

> You don't plan on keeping adding new items to the mapping dictionaries across multiple files every time someone adds a new model and a folder, don't you? :-)

Hope so, we have recently discussed this internally. We might infer the "mapping" dynamically as we already have all necessary bits defined in each config and model class.

**Comment by mostafatouny** [comment]
@zucchini-nlp, is it solved or moved to another issue?

**Comment by zucchini-nlp** [comment]
Oh sorry, gh closed the issue without any contribution. I will open PR today

**Comment by zucchini-nlp** [comment]
I missed tat it was actually fixed in https://github.com/huggingface/transformers/pull/44672, but not linked to the issue. Checked with last release and works fine :)
