### PR TITLE
Support for torch-lightning in NER examples

### PR DESCRIPTION
**Pull request by srush**
Update of https://github.com/huggingface/transformers/pull/2816

This PR creates a new example coding style for the pytorch code.

* Uses pytorch-lightning for the underlying training.
* Separates out the base transformer loading from the individual training.
* Moves each individual example to its own directory.
* Move the code in the readme to bash scripts.
The only two new files are run_pl_ner.py and transformers_base.py.

The goal is to keep the same format as the original command-line. Most of the argument names are preserved. I have verified that for NER the results of the same on GPU.

There are several nice benefits of lightning -> somewhat nicer logging and library integration (e.g. wandb), auto-checkpointing. Mostly the goal though is code readability with identical functionality.

Tests I ran:

* make sure that the test results are identical.
* print test results after training.
* test multi-gpu and apex (multigpu gives a nice speedup)

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
This is cool and clean. Thanks @srush !

**Comment by simonepri** [comment]
@LysandreJik 
This implementation does not work with `pytorch_lightning` > `0.7.1`.

It throws the exception `'Trainer' object has no attribute 'avg_loss'` because since version `0.7.2` they removed the `avg_loss` field from the `Trainer` class.

See https://github.com/huggingface/transformers/pull/2890/files#diff-d68a6ecfacd8231c59af0ea67d77bb9cR120

**Comment by srush** [comment]
@simonepri can you file an issue? I guess we should just remove that key/value pair.

**Comment by williamFalcon** [comment]
@simonepri did you try 0.7.5?
