### PR TITLE
bump Torch 2.1 with broken compatibility `torch.compile`

### LINKED ISSUE #37238: transformers 4.50 does not work with pytorch 2.0
### System Info

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

results in 

```
RuntimeError: Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
module 'torch' has no attribute 'compiler'
```

I cannot run `transformers-cli env` for the same reason.

transformers 4.49 does not have this issue.

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
pip install torch==2.0.1  transformers==4.50.3
python <<-EOF
from transformers.integrations import CodeCarbonCallback
EOF
```

### Expected behavior

it should not give an error.

transformers 4.49 does not have this issue.

### PR DESCRIPTION
**Pull request by Borda**
# What does this PR do?

This PR updates the minimum required version of Torch to 2.1 due to an issue with `torch.compile` in 2.0. The problem was identified through Dependabot in [#3027](https://github.com/Lightning-AI/torchmetrics/pull/3027), where all versions passed except for 2.0.

Fixes #37238

Issue Details

When running tests with Torch 2.0, we encountered the following error:
```py
@torch.compiler.disable(recursive=False)
AttributeError: module 'torch' has no attribute 'compiler'
```

This happens because `torch.compiler` does not exist in 2.0, causing failures in dependencies like transformers.

**Changes**
- Set the minimum Torch version to 2.1 to ensure compatibility with `torch.compile`.
- Updated relevant dependencies accordingly.

**Impact**
- This update ensures that `torch.compile` is available and avoids compatibility issues.
- Users running Torch 2.0 will need to upgrade to 2.1 or higher.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

well, this is eventually affecting multiple domains...

Models:

- text models: @ArthurZucker
- vision models: @amyeroberts, @qubvel
- speech models: @eustlb
- graph models: @clefourrier

### CODE REVIEW

**Comment by Rocketknight1** [comment]
I'm okay with bumping the dependency - `2.0` is quite old by now. cc core maintainers @arthurzucker @cyrilvallez

**Comment by Cyrilvallez** [comment]
It's fine by me, but cc @ArthurZucker for final decision about that

**Comment by qubvel** [comment]
also reported in https://github.com/huggingface/transformers/issues/37238

**Comment by ydshieh** [comment]
it's in my plan to drop the support of torch 2.0: internally, we drop the support of a torch major version that is released more than 2 years ago, and torch 2.0 is released in March 15 2023.

**Comment by ydshieh** [comment]
Looks like I am not able to push the branch. I will open another PR for this.

**Comment by ydshieh** [comment]
Hi @Borda I'm closing this PR and we will go with #37277. 

But thank you a lot for this work!

**Comment by Borda** [comment]
when will this be released?
