### ISSUE TITLE
transformers.exporters raises ImportError on torch < 2.8 while setup.py declares torch>=2.5

### ISSUE THREAD

**Issue by Neal006** [huggingface/transformers#47710]
### System Info

- transformers version: 5.15.0.dev0 (`main`, commit `b3a36037d3feb22e3f0174b3dd4248fcc0f0f722`)
- Platform: Windows-11-10.0.26200-SP0
- Python version: 3.13.2
- Huggingface_hub version: 1.20.1
- Safetensors version: 0.8.0
- PyTorch version: 2.6.0+cu124 (CUDA available: True)

### Who can help?

@IlyasMoutawwakil

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

`import transformers.exporters` fails on torch 2.6.0, which is inside the declared `torch>=2.5`
support range:

```python
>>> import transformers.exporters
ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

```python
>>> from transformers.exporters import AutoHfExporter
ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

`src/transformers/exporters/exporter_executorch.py` imports the symbol at module scope:

```python
if is_torch_available():
    import torch
    from torch.export import ExportedProgram
    from torch.fx.experimental.symbolic_shapes import guard_or_true
```

`guard_or_true` was added in torch 2.8, where it replaced `definitely_true`. `setup.py` and
`dependency_versions_table.py` declare `torch>=2.5`. `is_torch_available()` checks that torch is
installed, not which version, so the import runs and fails on torch 2.5, 2.6 and 2.7.

`src/transformers/exporters/auto.py` imports the ExecuTorch exporter eagerly:

```python
from .exporter_executorch import ExecutorchConfig, ExecutorchExporter
```

so the ONNX and Dynamo exporters are unreachable as well, on torch versions neither of them needs.

`python utils/checkers.py imports, repo` also fails on `main` for the same reason under torch < 2.8.

`tests/exporters/` cannot be collected at all:

```
tests/exporters/test_export.py:24: in <module>
    from transformers.exporters.exporter_dynamo import DynamoConfig, DynamoExporter
E   ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

First bad commit is `fde2b96b5` (#41992). The module-level import has been present since the
exporters package was added.

### Expected behavior

`transformers.exporters` should import on any supported torch version, and requesting an exporter
whose requirements are not met should raise the error the package already defines for that case.

`HfExporter` in `exporters/base.py` has the mechanism:

```python
# Hard minimum versions — the exporter raises below these (features it relies on are absent).
min_versions: dict[str, str] = {}
```

`DynamoExporter` declares it and produces an actionable message:

```
ImportError: DynamoExporter requires newer versions of: torch>=2.11.0 (found 2.6.0+cu124)
```

`ExecutorchExporter` declares `required_packages` and `tested_versions` but no `min_versions`, even
though it depends on a torch 2.8 symbol. Expressing that dependency as a module-level import
bypasses the gate and turns a clear message into an import failure that takes the sibling exporters
with it.

Two options:

1. Move the `guard_or_true` import into `_patch_remove_empty_tensors_from_cat`, the only function
   that uses it at module scope, and add `min_versions = {"torch": "2.8.0"}` to `ExecutorchExporter`.
   The sibling patch handler in the same file, `_patch_dim_order_from_stride`, already imports
   `guard_or_false, guard_or_true` function-locally, so this matches existing convention.
2. Raise the declared torch floor in `setup.py` and `dependency_versions_table.py` to 2.8.

I have option 1 working locally and can open a PR. Option 2 is a wider decision and yours to make.

### How I found this

I ran the repository's own consistency suite against `main` on torch 2.6.0:

```
python utils/checkers.py auto_mappings, imports, repo, ... --keep-going
```

`imports` and `repo` both failed with this ImportError, which is what led to the module-level import.
I then confirmed the symbol is absent from `torch.fx.experimental.symbolic_shapes` on 2.6.0,
checked when it was introduced upstream, and used `git log -S guard_or_true` to find the commit
that added the line.
