### ISSUE TITLE
'MERTConfig' object has no attribute 'conv_pos_batch_norm'

### ISSUE THREAD

**Issue by Timothy-John** [huggingface/transformers#36134]
### System Info

https://huggingface.co/m-a-p/MERT-v1-95M

This model works fine on transformers==4.47.1
But starting 4.48.0 (Tried till 4.48.3) this error was seen:
'MERTConfig' object has no attribute 'conv_pos_batch_norm'

@ylacombe, @eustlb could you please take a look..

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to repro as given in the page https://huggingface.co/m-a-p/MERT-v1-95M :

```
# from transformers import Wav2Vec2Processor
from transformers import Wav2Vec2FeatureExtractor
from transformers import AutoModel
import torch
from torch import nn
import torchaudio.transforms as T
from datasets import load_dataset


# loading our model weights
model = AutoModel.from_pretrained("m-a-p/MERT-v1-95M", trust_remote_code=True)
# loading the corresponding preprocessor config
processor = Wav2Vec2FeatureExtractor.from_pretrained("m-a-p/MERT-v1-95M",trust_remote_code=True)

# load demo audio and set processor
dataset = load_dataset("hf-internal-testing/librispeech_asr_demo", "clean", split="validation")
dataset = dataset.sort("id")
sampling_rate = dataset.features["audio"].sampling_rate

resample_rate = processor.sampling_rate
# make sure the sample_rate aligned
if resample_rate != sampling_rate:
    print(f'setting rate from {sampling_rate} to {resample_rate}')
    resampler = T.Resample(sampling_rate, resample_rate)
else:
    resampler = None

# audio file is decoded on the fly
if resampler is None:
    input_audio = dataset[0]["audio"]["array"]
else:
  input_audio = resampler(torch.from_numpy(dataset[0]["audio"]["array"]))
  
inputs = processor(input_audio, sampling_rate=resample_rate, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs, output_hidden_states=True)

# take a look at the output shape, there are 13 layers of representation
# each layer performs differently in different downstream tasks, you should choose empirically
all_layer_hidden_states = torch.stack(outputs.hidden_states).squeeze()
print(all_layer_hidden_states.shape) # [13 layer, Time steps, 768 feature_dim]

# for utterance level classification tasks, you can simply reduce the representation in time
time_reduced_hidden_states = all_layer_hidden_states.mean(-2)
print(time_reduced_hidden_states.shape) # [13, 768]

# you can even use a learnable weighted average representation
aggregator = nn.Conv1d(in_channels=13, out_channels=1, kernel_size=1)
weighted_avg_hidden_states = aggregator(time_reduced_hidden_states.unsqueeze(0)).squeeze()
print(weighted_avg_hidden_states.shape) # [768]
```

### Expected behavior

Should give outputs as mentioned in the official page

**Comment by Rocketknight1** [comment]
Hi @Timothy-John, this is a duplicate of the issue at #35656. We can't really fix this - the problem is that the MERT custom code imports from the Hubert model in the Transformers codebase, but an update to Hubert broke MERT. The MERT code needs to be updated **in the MERT repos, not in Transformers, since it's a custom code model!**

Please raise the issue on their repos and/or open a PR to replace the Hubert imports with actual code in the repo (which could be copied from older versions of Transformers when MERT still worked)
