### PR TITLE
Llama: allow custom 4d masks

### LINKED ISSUE #29525: custom 4d attention masks broken by #28937
### System Info

The 4.38.2 version breaks code using custom 4d attention masks (introduced in #27539). Apparently, the custom masks gets replaced here:https://github.com/huggingface/transformers/blob/4ed9ae623d16876ad84ea89dfdf1c9378e36961b/src/transformers/models/llama/modeling_llama.py#L660-L662

The issue was introduced with #28937. It is unclear whether the relevant slow tests for 4d masks were run then, but they fail now:
```
RUN_SLOW=1 python -m pytest -v ./tests/test_modeling_utils.py::Mask4DTestFP32
FAILED tests/test_modeling_utils.py::Mask4DTestFP32::test_attention - AttributeError: 'NoneType' object has no attribute 'shape'
FAILED tests/test_modeling_utils.py::Mask4DTestFP32::test_causal_model_logits - AssertionError: Tensor-likes are not close!
FAILED tests/test_modeling_utils.py::Mask4DTestFP32::test_inner_model - AssertionError: Tensor-likes are not close!

RUN_SLOW=1 python -m pytest -v ./tests/test_modeling_utils.py::Mask4DTestFP16
FAILED tests/test_modeling_utils.py::Mask4DTestFP16::test_attention - AttributeError: 'NoneType' object has no attribute 'shape'
FAILED tests/test_modeling_utils.py::Mask4DTestFP16::test_causal_model_logits - AssertionError: Tensor-likes are not close!
```
please fix or suggest workaround

summoning @ArthurZucker 
cc @gante @younesbelkada

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Fixes #29525 

Reintroduces the ability to pass custom 4D attention masks, which was removed in the static cache transition. The following tests are now passing
```
RUN_SLOW=1 python -m pytest -v ./tests/test_modeling_utils.py::Mask4DTestFP32
RUN_SLOW=1 python -m pytest -v ./tests/test_modeling_utils.py::Mask4DTestFP16
```

cc @ArthurZucker after you come back from holidays, have a look at this PR :)

### CODE REVIEW

File: tests/test_modeling_utils.py [hunk 1]
```diff
@@ -1997,81 +1999,63 @@ def get_test_data(self):
...
 
     def test_attention(self):
         """comparing outputs of attention layer"""
-        input_0, input_1, mask_1, position_ids_1 = self.get_test_data()
+        input_0, position_ids_0, input_1, mask_1, position_ids_1 = self.get_test_data()
+        causal_mask_1 = (1 - mask_1).to(self.model_dtype) * torch.finfo(self.model_dtype).min
 
         hid_0 = self.model.model.embed_tokens(input_0)
-        outs_0 = self.model.model.layers[0].self_attn.forward(hid_0)[0]
+        outs_0 = self.model.model.layers[0].self_attn.forward(hid_0, position_ids=position_ids_0)[0]
```
Comment (gante) [inline tests/test_modeling_utils.py:2019]: `position_ids` is now a "mandatory" input to the attention layer forward

File: tests/test_modeling_utils.py [hunk 2]
```diff
@@ -1997,81 +1999,63 @@ def get_test_data(self):
...
         # outs_0.shape == torch.Size([3, 4, 768])
 
         hid_1 = self.model.model.embed_tokens(input_1)
         outs_1 = self.model.model.layers[0].self_attn.forward(
-            hid_1, attention_mask=mask_1.bool(), position_ids=position_ids_1
+            hid_1, attention_mask=causal_mask_1, position_ids=position_ids_1
```
Comment (gante) [inline tests/test_modeling_utils.py:2024]: the attention layer forward now expects numerical 4D causal masks (as opposed to 2D boolean masks)

File: tests/test_modeling_utils.py [hunk 3]
```diff
@@ -1997,81 +1999,63 @@ def get_test_data(self):
...
         )[0]
         # outs_1.shape == torch.Size([1, 6, 768])
 
         outs_0_last_tokens = outs_0[:, -1, :]  # last tokens in each batch line
         outs_1_last_tokens = outs_1[0, -3:, :]  # last three tokens
-        assert torch.allclose(outs_0_last_tokens, outs_1_last_tokens)
-
-    def test_inner_model(self):
```
Comment (gante) [inline tests/test_modeling_utils.py:2030]: This test was a copy of the test below 🤔

**Review by amyeroberts — APPROVED** [review]
Thanks for reenabling this! 

Only question before merge is how come this is only needed for the gemma and llama models?
