### PR TITLE
Deprecate old past arguments

### PR DESCRIPTION
**Pull request by sgugger**
As discussed internally, previous arguments `past`, `decoder_cached_states` and `decoder_past_key_value_states` are deprecated and replaced by either `past_key_values` or `decoder_past_key_values`. 
This also fixes the mentions to those arguments in the input docstrings, the output docstrings already refer to the correct arg (this was done in #5226 ).

In passing, replace `DeprecationWarning` in the other deprecated args by `FutureWarning`, since it's the right way to do it.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
This is very cool, nice to keep the backwards compatibility.

**Comment by mahimanzum** [comment]
i was able to use gpt2 using trainer 10-12 hours ago but i am getting an error now, i think the "past" variable replacing is not consistent with the trainer.py class that's why i am getting this error

TypeError                                 Traceback (most recent call last)
<ipython-input-15-3435b262f1ae> in <module>
----> 1 trainer.train()

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/trainer.py in train(self, model_path)
    497                     continue
    498 
--> 499                 tr_loss += self._training_step(model, inputs, optimizer)
    500 
    501                 if (step + 1) % self.args.gradient_accumulation_steps == 0 or (

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/trainer.py in _training_step(self, model, inputs, optimizer)
    620             inputs["mems"] = self._past
    621 
--> 622         outputs = model(**inputs)
    623         loss = outputs[0]  # model outputs are always tuple in transformers (see doc)
    624 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    530             result = self._slow_forward(*input, **kwargs)
    531         else:
--> 532             result = self.forward(*input, **kwargs)
    533         for hook in self._forward_hooks.values():
    534             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    151         replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
    152         outputs = self.parallel_apply(replicas, inputs, kwargs)
--> 153         return self.gather(outputs, self.output_device)
    154 
    155     def replicate(self, module, device_ids):

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py in gather(self, outputs, output_device)
    163 
    164     def gather(self, outputs, output_device):
--> 165         return gather(outputs, output_device, dim=self.dim)
    166 
    167 

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py in gather(outputs, target_device, dim)
     66     # Setting the function to None clears the refcycle.
     67     try:
---> 68         res = gather_map(outputs)
     69     finally:
     70         gather_map = None

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py in gather_map(outputs)
     61             return type(out)(((k, gather_map([d[k] for d in outputs]))
     62                               for k in out))
---> 63         return type(out)(map(gather_map, zip(*outputs)))
     64 
     65     # Recursive function calls like this create reference cycles.

TypeError: __init__() missing 1 required positional argument: 'logits'

**Comment by sgugger** [comment]
This is not linked to this PR, as the Trainer never uses past. It seems linked to the model output PR (#5226) will push a quick fix soon.

**Comment by mahimanzum** [comment]
Then why the trainer that works in 3.0.1 does not work after this PR merge.
I am new to this library and trying to understand it would be very helpful
if you explained a bit.
Thanks

**Comment by sgugger** [comment]
I think you mistake the PR that caused the problem, #5226 was merged just a bit before.
