### PR TITLE
Fix ImportError in transformers.exporters on torch < 2.8

### LINKED ISSUE #47710: transformers.exporters raises ImportError on torch < 2.8 while setup.py declares torch>=2.5
### System Info

- transformers version: 5.15.0.dev0 (`main`, commit `b3a36037d3feb22e3f0174b3dd4248fcc0f0f722`)
- Platform: Windows-11-10.0.26200-SP0
- Python version: 3.13.2
- Huggingface_hub version: 1.20.1
- Safetensors version: 0.8.0
- PyTorch version: 2.6.0+cu124 (CUDA available: True)

### Who can help?

@IlyasMoutawwakil

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

`import transformers.exporters` fails on torch 2.6.0, which is inside the declared `torch>=2.5`
support range:

```python
>>> import transformers.exporters
ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

```python
>>> from transformers.exporters import AutoHfExporter
ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

`src/transformers/exporters/exporter_executorch.py` imports the symbol at module scope:

```python
if is_torch_available():
    import torch
    from torch.export import ExportedProgram
    from torch.fx.experimental.symbolic_shapes import guard_or_true
```

`guard_or_true` was added in torch 2.8, where it replaced `definitely_true`. `setup.py` and
`dependency_versions_table.py` declare `torch>=2.5`. `is_torch_available()` checks that torch is
installed, not which version, so the import runs and fails on torch 2.5, 2.6 and 2.7.

`src/transformers/exporters/auto.py` imports the ExecuTorch exporter eagerly:

```python
from .exporter_executorch import ExecutorchConfig, ExecutorchExporter
```

so the ONNX and Dynamo exporters are unreachable as well, on torch versions neither of them needs.

`python utils/checkers.py imports, repo` also fails on `main` for the same reason under torch < 2.8.

`tests/exporters/` cannot be collected at all:

```
tests/exporters/test_export.py:24: in <module>
    from transformers.exporters.exporter_dynamo import DynamoConfig, DynamoExporter
E   ImportError: cannot import name 'guard_or_true' from 'torch.fx.experimental.symbolic_shapes'
```

First bad commit is `fde2b96b5` (#41992). The module-level import has been present since the
exporters package was added.

### Expected behavior

`transformers.exporters` should import on any supported torch version, and requesting an exporter
whose requirements are not met should raise the error the package already defines for that case.

`HfExporter` in `exporters/base.py` has the mechanism:

```python
# Hard minimum versions — the exporter raises below these (features it relies on are absent).
min_versions: dict[str, str] = {}
```

`DynamoExporter` declares it and produces an actionable message:

```
ImportError: DynamoExporter requires newer versions of: torch>=2.11.0 (found 2.6.0+cu124)
```

`ExecutorchExporter` declares `required_packages` and `tested_versions` but no `min_versions`, even
though it depends on a torch 2.8 symbol. Expressing that dependency as a module-level import
bypasses the gate and turns a clear message into an import failure that takes the sibling exporters
with it.

Two options:

1. Move the `guard_or_true` import into `_patch_remove_empty_tensors_from_cat`, the only function
   that uses it at module scope, and add `min_versions = {"torch": "2.8.0"}` to `ExecutorchExporter`.
   The sibling patch handler in the same file, `_patch_dim_order_from_stride`, already imports
   `guard_or_false, guard_or_true` function-locally, so this matches existing convention.
2. Raise the declared torch floor in `setup.py` and `dependency_versions_table.py` to 2.8.

I have option 1 working locally and can open a PR. Option 2 is a wider decision and yours to make.

### How I found this

I ran the repository's own consistency suite against `main` on torch 2.6.0:

```
python utils/checkers.py auto_mappings, imports, repo, ... --keep-going
```

`imports` and `repo` both failed with this ImportError, which is what led to the module-level import.
I then confirmed the symbol is absent from `torch.fx.experimental.symbolic_shapes` on 2.6.0,
checked when it was introduced upstream, and used `git log -S guard_or_true` to find the commit
that added the line.

### PR DESCRIPTION
**Pull request by Neal006**
[CI](https://transformers-ci.lor-e.huggingface.cool/d/pytest-observability-by-pr/pytest-observability-branch?var-pr=47711)

# What does this PR do?

Fixes #47710.

`import transformers.exporters` raises `ImportError` on torch 2.5, 2.6 and 2.7, all inside the
declared `torch>=2.5` support range. `exporter_executorch.py` imports `guard_or_true` at module
scope, and that symbol was added in torch 2.8 where it replaced `definitely_true`.
`is_torch_available()` checks that torch is installed, not which version, so the import runs and
fails. Because `exporters/auto.py` imports the ExecuTorch exporter eagerly, the ONNX and Dynamo
exporters become unreachable too, on torch versions neither of them needs.

First bad commit is `fde2b96b5` (#41992), found with `git log -S guard_or_true`.

## The change

One line moves. That is the whole diff.

`guard_or_true` moves into `_patch_remove_empty_tensors_from_cat`, the only function that uses it.
The sibling patch handler in the same file, `_patch_dim_order_from_stride`, already imports
`guard_or_false, guard_or_true` function-locally, so this follows existing convention.

No `min_versions` entry is added. An earlier revision of this PR declared
`min_versions = {"torch": "2.8.0"}` on `ExecutorchExporter`; that was wrong and has been dropped.
`min_versions` is a plain class attribute, so `ExecutorchExporter` already inherits
`{"torch": "2.11.0"}` from `DynamoExporter`, and declaring `2.8.0` here overrode it downward. That
would have let users past `validate_environment` on torch 2.8 to 2.10 and into a later failure
inside `DynamoExporter.export`. Thanks to the Copilot review for catching it. The inherited
`torch>=2.11.0` floor already covers `guard_or_true` by a wide margin, so this file needs no gate
of its own.

An earlier revision also added `tests/exporters/test_utils.py::ImportSurfaceTest`, asserting
`guard_or_true` is not a module global of `exporter_executorch`. Removed at @IlyasMoutawwakil's
request.

No new helper, no new dependency, no behavior change on torch >= 2.8.

## Verification on torch 2.6.0

| | before | after |
|---|---|---|
| `import transformers.exporters` | ImportError | OK |
| `from transformers.exporters import AutoHfExporter` | ImportError | OK |
| `AUTO_EXPORTER_MAPPING` | unreachable | `['dynamo', 'executorch', 'onnx']` |
| `python utils/checkers.py imports, repo` | FAILED | OK |
| `pytest tests/exporters/test_utils.py` | collection error, 0 run | 13 passed, 2 skipped, 1 failed |

The fix was verified against the bug: restoring the module-scope import makes the whole test file
fail collection on torch 2.6.

The one remaining failure, `test_from_config_dispatches_dynamo`, is
`DynamoExporter requires newer versions of: torch>=2.11.0 (found 2.6.0+cu124)`. That comes from
`DynamoExporter.min_versions` and my local torch, not from this change. It failed before this PR
too, silently, because nothing in the suite could be collected.

`ruff check` and `ruff format` are clean.

## Before submitting

- [x] Did you read the [contributor guideline](https://huggingface.co/docs/transformers/contributing)?
- [x] Was this discussed via a GitHub issue? #47710.
- [x] Did you write any new necessary tests? No, per reviewer request.

I used AI tooling to investigate this, and I have reviewed and verified every changed line and run
the tests and checks above myself.

## Who can review?

@IlyasMoutawwakil, since you authored #41992. Review, and merge if it looks right to you. Happy to
switch to raising the declared torch floor instead if you prefer that route.

### CODE REVIEW

File: src/transformers/exporters/exporter_executorch.py [hunk 1]
```diff
@@ -102,6 +101,7 @@ class ExecutorchExporter(DynamoExporter):
     """
 
     required_packages = ["torch", "executorch"]
+    min_versions = {"torch": "2.8.0"}
     tested_versions = {"torch": "2.12.0", "executorch": "1.3.1"}
```
[the remark this answers is not in the document]
Comment (Neal006) [reply src/transformers/exporters/exporter_executorch.py:104]: Good catch, fixed. You are right that this relaxed the floor rather than
tightening it: `min_versions` is a plain class attribute, so `ExecutorchExporter`
already inherited `{"torch": "2.11.0"}` from `DynamoExporter`, and declaring
`2.8.0` here overrode it. That would have let users past `validate_environment`
on torch 2.8 to 2.10 and then failed inside `DynamoExporter.export`, which is
worse than the clear error they get today.

The line is gone. The inherited `torch>=2.11.0` floor stands, and it already
covers `guard_or_true` (torch 2.8) by a wide margin, so nothing here needs a
gate of its own. The remaining diff is just the import move.

File: src/transformers/exporters/exporter_executorch.py [hunk 2]
```diff
@@ -494,6 +494,7 @@ def _patch_remove_empty_tensors_from_cat(_original):
     inputs conservatively (the pass is purely an optimisation).
     """
     from executorch.exir.dialects._ops import ops as exir_ops
+    from torch.fx.experimental.symbolic_shapes import guard_or_true
 
     def patch(self, graph_module, cat_node):
         pruned = [arg for arg in cat_node.args[0] if guard_or_true(arg.meta["val"].numel() != 0)]
```
[the remark this answers is not in the document]
Comment (Neal006) [reply src/transformers/exporters/exporter_executorch.py:499]: Added a test, though not quite the one suggested. Deleting `guard_or_true` and
reimporting the module means `importlib.reload`, which re-runs the ~25
`register_patch` / `register_fx_*_fix` decorators in this file against the
global registries and leaks that state into every test after it.

`tests/exporters/test_utils.py::ImportSurfaceTest` asserts instead that
`guard_or_true` is not in `vars(exporter_executorch)`, which fails on exactly
the regression you describe with no reload and no side effects. Verified by
putting the module-scope import back: the whole test file then fails collection
on torch 2.6.

File: tests/exporters/test_utils.py [hunk 3]
```diff
@@ -132,6 +132,20 @@ def test_from_config_raises_on_unknown_format(self):
...
+    torch than `setup.py` declares (`torch>=2.5`) takes the whole `transformers.exporters` package
+    down when imported at module scope — ONNX and Dynamo included. Version-gated symbols belong
+    inside the function that uses it."""
+
+    @require_torch
+    def test_guard_or_true_is_not_imported_at_module_scope(self):
+        from transformers.exporters import exporter_executorch
+
+        # `guard_or_true` landed in torch 2.8.
+        self.assertNotIn("guard_or_true", vars(exporter_executorch))
```
Comment (IlyasMoutawwakil) [inline tests/exporters/test_utils.py]: no need

**Comment by IlyasMoutawwakil** [comment]
thanks, just remove the test please

**Review by IlyasMoutawwakil — APPROVED** [review]
